= Authentication Methods

You can configure Anypoint CLI authentication with username and password, client ID and client secret, or a bearer token.
At least one method is required.

[[username-pw]]
=== Username and Password

If you don't log in using single sign-on (SSO), you can use your username and password to log into the CLI directly.

[%header%autowidth.spread,cols="a,a"]
|===
| Parameter | Description
| `username` | Your Anypoint Platform username

You can also pass this value using the environment variable `export ANYPOINT_USERNAME=<name>`.
| `password` | Your Anypoint Platform password

You can also pass this value using the environment variable `export ANYPOINT_PASSWORD=<pwd>`.
|===

For information about logging in using SSO, see xref:access-management::external-identity.adoc[About Identity Management].

[[client-id-secret]]
=== Client ID and Client Secret

You can configure a Connected App with the `client_credentials` grant type to use with the CLI.

[%header%autowidth.spread,cols="a,a"]
|===
| Parameter | Description
| `client_id` | The ID of the Connected App

You can also pass this value using the environment variable `export ANYPOINT_CLIENT_ID=<client_id>`.
| `client_secret` | The client secret of the Connected App

You can also pass this value using the environment variable `export ANYPOINT_CLIENT_SECRET=<client_secret>`.
|===

For more information about Connected Apps, see xref:access-management::connected-apps-overview.adoc[Connected Apps].

[[bearer-token]]
=== Bearer Token

If you have already generated a bearer token, you can pass it to the CLI directly.
When you provide a bearer token, the CLI ignores any provided user or client credentials.

[%header%autowidth.spread,cols="a,a"]
|===
| Parameter | Description
| `bearer` | A bearer token for the Anypoint Platform

Your CLI session expires when the bearer token expires.
|===

For information about generating a bearer token, see https://help.mulesoft.com/s/article/How-to-generate-your-Authorization-Bearer-token-for-Anypoint-Platform[How to generate your Authorization Bearer token for Anypoint Platform].

[[credentials-file]]
=== Credentials File

The recommended way of passing these options to your Anypoint Platform CLI installation is using the `credentials` file located inside the `~/.anypoint` directory, which is not automatically created during installation. Follow these steps to create your credentials file:

. Create a directory called `.anypoint` in the `~/` directory for Linux and OSx, or `C:\Users\USERNAME \` in Windows.
. Navigate to your `.anypoint` directory and create a blank file named `credentials` with the following structure:
+
[source,text,linenums]
----
{
 "default": {
  "username": "yourAnypointUserName",
  "password": "yourAnypointPassword",
  "organization": "",
  "environment": "",
  "host": ""
 },
 "otherProfile": {
  "username": "",
  "password": "",
  "organization": "",
  "environment": "",
  "host": ""
 },
 "connAppProfile": {
  "client_id": "",
  "client_secret": "",
  "organization": "",
  "environment": "",
  "host": ""
 }
}
----
Note that the `default` profile is used unless the `ANYPOINT_PROFILE` environment variable is set:
+
[source,text,linenums]
----
> export ANYPOINT_PROFILE="otherProfile"
> anypoint-cli
----

Then run the `anypoint-cli` command without any options:

[source,text,linenums]
----
> anypoint-cli
----

[[env-variables]]
=== Dedicated Environment Variables

If you choose to pass the credentials when running `anypoint-cli`, pass both parameters as environment variables: `ANYPOINT_USERNAME` and `ANYPOINT_PASSWORD`.

[source,text,linenums]
----
> export ANYPOINT_USERNAME="username"
> export ANYPOINT_PASSWORD="password"
> anypoint-cli
----

[[cli-options]]
=== CLI Options

If you pass only your username, the Anypoint CLI prompts for your password.

[source,text,linenums]
----
> anypoint-cli --username="user"
Password: ****
----