= Authentication Methods

You can pass Anypoint CLI credentials using the following methods:

* <<credentials-file,Using a credentials configuration file (Recommended)>>
* <<command-line-parameters,Using command line parameters>>
* <<env-variables,Using environment variables>>

Configuration settings are overridden in the following order:

* Command line parameters override all other methods. 

* Environment variables are used if command line parameters are not specified and override any credentials configuration file settings.

* Credentials configuration file parameters are used if no command line parameters or environment variables are set.

Each method of passing credentials enables you to authenticate Anypoint CLI with username and password, client ID and client secret, or a bearer token:

* <<username-pw>>
* <<client-id-secret>>
* <<bearer-token>>

[[credentials-file]]
=== Credentials Configuration File

MuleSoft recommends that you pass credentials to your Anypoint Platform CLI installation using the credentials configuration file for optimal security. 
You can authenticate to Anypoint Platform with username and password, client ID and client secret, or a bearer token using a combination of the following parameters:

username, password, client_id, client_secret, host, session.selectedEnvironment.id, session.selectedOrganization.id

To create your configuration file:

* Run the "anypoint-cli-v4 conf" command with the parameters you want to use to set the authentication method. For example, the following command sets the username and password.
+
----
$ anypoint-cli-v4 conf username <username>
$ anypoint-cli-v4 conf password <password>
----

The commands store the credential information in the `config.json` file in the following locations:

* MacOS: `~/Library/Preferences/@mulesoft/anypoint-cli-v4-nodejs/config.json`

* Windows: `%LOCALAPPDATA%\mycli`

* Unix: `~/.config/mycli`

[[command-line-parameters]]
== Command Line Parameters

You can authenticate to Anypoint Platform with username and password, client ID and client secret, or a bearer token by running the `anypoint-cli-v4` command with a combination of the following parameters:

--username, --password, --client_id, --client_secret, --bearer, --organization, --environment

For details see the following:

* <<username-pw>>
* <<client-id-secret>>
* <<bearer-token>>

[[env-variables]]
=== Dedicated Environment Variables

You can authenticate to Anypoint Platform with username and password, client ID and client secret, or a bearer token using a combination of the following environment variables:

ANYPOINT_USERNAME, ANYPOINT_PASSWORD, ANYPOINT_CLIENT_ID, ANYPOINT_CLIENT_SECRET, ANYPOINT_ORG, ANYPOINT_ENV, ANYPOINT_HOST

For details see the following:

* <<username-pw>>
* <<client-id-secret>>
* <<bearer-token>>

[source,text,linenums]
----
> export ANYPOINT_USERNAME="username"
> export ANYPOINT_PASSWORD="password"
> anypoint-cli
----

[[username-pw]]
=== Username and Password

If you do not log in using single sign-on (SSO), you can use your username and password to log into the CLI directly.

[%header%autowidth.spread,cols="a,a"]
|===
| Parameter | Description
| `username` | Your Anypoint Platform username

You can also pass this value using the environment variable `export ANYPOINT_USERNAME=<name>`.
| `password` | Your Anypoint Platform password

You can also pass this value using the environment variable `export ANYPOINT_PASSWORD=<pwd>`.
|===

If you choose to pass the credentials when running `anypoint-cli-v4`, pass both parameters as environment variables: `ANYPOINT_USERNAME` and `ANYPOINT_PASSWORD`.

For information about logging in using SSO, see xref:access-management::external-identity.adoc[About Identity Management].

[[client-id-secret]]
=== Client ID and Client Secret

You can configure a Connected App with the `client_credentials` grant type to use with the CLI.

[%header%autowidth.spread,cols="a,a"]
|===
| Parameter | Description
| `client_id` | The ID of the Connected App

You can also pass this value using the environment variable `export ANYPOINT_CLIENT_ID=<client_id>`.
| `client_secret` | The client secret of the Connected App

You can also pass this value using the environment variable `export ANYPOINT_CLIENT_SECRET=<client_secret>`.
|===

For more information about Connected Apps, see xref:access-management::connected-apps-overview.adoc[Connected Apps].

[[bearer-token]]
=== Bearer Token

If you have already generated a bearer token, you can pass it to the CLI directly.
When you provide a bearer token, the CLI ignores any provided user or client credentials.

[%header%autowidth.spread,cols="a,a"]
|===
| Parameter | Description
| `bearer` | A bearer token for the Anypoint Platform

Your CLI session expires when the bearer token expires.
|===

For information about generating a bearer token, see https://help.mulesoft.com/s/article/How-to-generate-your-Authorization-Bearer-token-for-Anypoint-Platform[How to generate your Authorization Bearer token for Anypoint Platform].
