= Authentication Methods

You can configure Anypoint CLI authentication with username and password, client ID and client secret, or a bearer token.
At least one method is required.

You can optionally set environment variables to hold the credential values or create a credentials file. See the following sections for details.

* <<username-pw>>
* <<client-id-secret>>
* <<bearer-token>>
* <<config-file>>
* <<env-variables>>

[[username-pw]]
=== Username and Password

If you do not log in using single sign-on (SSO), you can use your username and password to log into the CLI directly.

[%header%autowidth.spread,cols="a,a"]
|===
| Parameter | Description
| `username` | Your Anypoint Platform username

You can also pass this value using the environment variable `export ANYPOINT_USERNAME=<name>`.
| `password` | Your Anypoint Platform password

You can also pass this value using the environment variable `export ANYPOINT_PASSWORD=<pwd>`.
|===

For information about logging in using SSO, see xref:access-management::external-identity.adoc[About Identity Management].

[[client-id-secret]]
=== Client ID and Client Secret

You can configure a Connected App with the `client_credentials` grant type to use with the CLI.

[%header%autowidth.spread,cols="a,a"]
|===
| Parameter | Description
| `client_id` | The ID of the Connected App

You can also pass this value using the environment variable `export ANYPOINT_CLIENT_ID=<client_id>`.
| `client_secret` | The client secret of the Connected App

You can also pass this value using the environment variable `export ANYPOINT_CLIENT_SECRET=<client_secret>`.
|===

For more information about Connected Apps, see xref:access-management::connected-apps-overview.adoc[Connected Apps].

[[bearer-token]]
=== Bearer Token

If you have already generated a bearer token, you can pass it to the CLI directly.
When you provide a bearer token, the CLI ignores any provided user or client credentials.

[%header%autowidth.spread,cols="a,a"]
|===
| Parameter | Description
| `bearer` | A bearer token for the Anypoint Platform

Your CLI session expires when the bearer token expires.
|===

For information about generating a bearer token, see https://help.mulesoft.com/s/article/How-to-generate-your-Authorization-Bearer-token-for-Anypoint-Platform[How to generate your Authorization Bearer token for Anypoint Platform].

[[config-file]]
=== Configuration File

MuleSoft recommends that you pass credentials to your Anypoint Platform CLI installation using the Node.js `config.json` file. 

To create your configuration file:

. Run the "anypoint-cli-v4 conf" command, to set the authentication method.
+
----
$ anypoint-cli-v4 conf username <username>
$ anypoint-cli-v4 conf password <password>
----
+
The `config.json` file is created in the following directory:
+
 ~/Library/Preferences/@mulesoft/anypoint-cli-v4-nodejs/config.json

[[env-variables]]
=== Dedicated Environment Variables

If you choose to pass the credentials when running `anypoint-cli`, pass both parameters as environment variables: `ANYPOINT_USERNAME` and `ANYPOINT_PASSWORD`.

[source,text,linenums]
----
> export ANYPOINT_USERNAME="username"
> export ANYPOINT_PASSWORD="password"
> anypoint-cli
----