= Installing Anypoint CLI 4.x

You must install Anypoint CLI from npm before you can run the commands. Use the following guidelines to install:

* <<prereqs,Install the prerequisite software>> before proceeding with the Anypoint CLI installation. 

* <<installation,Install the Anypoint CLI 4.x package>>, which includes all of the default plugins.

* <<install-plugins,Install non-default plugins or new versions of default plugins>> if needed after you have installed Anypoint CLI 4.x. 

* <<verify-installation,Verify the installation>>.

* If you want to remove plugins you do not use, you can selectively <<uninstall-plugins,uninstall plugins>>.

See the <<plugin-list,list of Anypoint CLI plugins>> to see which plugins are available.

[[prereqs]]
== Before You Begin

The Anypoint CLI is built with Node.js and is installed by using npm (node package manager).

Versions required are as follows:

* Node.js version 16 or later
* npm version 7 or later

To install the prerequisite software:

* Download and install Node.js and npm.
+
See the https://nodejs.org/en/download/[NodeJS download page].

Depending on the configuration of your system, you might need to log in using administrator credentials before you can successfully run the npm commands.


[[plugin-list]]
== List of Plugins

You can install the following plugins with Anypoint CLI:  

[%header,cols="35a,65a"]
|===
|Plugin |Description
| anypoint-cli-account-plugin | Account command topics
| anypoint-cli-api-mgr-plugin | API Manager command topics
| anypoint-cli-cloudhub-plugin | CloudHub command topics
| anypoint-cli-designcenter-plugin | Design Center command topics
| anypoint-cli-datagraph-plugin | DataGraph command topics
| anypoint-cli-exchange-plugin| Exhange command topics
| anypoint-cli-runtime-mgr-plugin | Runtime Manager command topics
|===

[[installation]]
== Install the Core Package Plus Default Plugins

Run the following command to install the Anypoint CLI core package plus all default plugins. See <<plugin-list,List of Plugins>>.

[source,text,linenums]
----
$ npm install -g @mulesoft/anypoint-cli-v4
----

[[install-plugins]]
== Install a Plugin Separately

After you have installed the Anypoint CLI 4.x core package you can install plugins that are not included with Anypoint CLI by default or install a new version of a default plugin. Install each of the plugins you want to use as follows:

[source,text,linenums]
----
$ anypoint-cli-v4 plugins:install @mulesoft/<plugin-name>
----

For example, to install the account plugin, use the following command:

[source,text,linenums]
----
$ anypoint-cli-v4 plugins:install @mulesoft/anypoint-cli-account-plugin
----

See <<plugin-list>>.

[[verify-installation]]
== Verify the Installation

After you install Anypoint CLI you can verify the installation as follows:

* <<view-core-version>>
* <<view-plugin-list>>
* <<view-all-version-info>>

[[view-core-version]]
=== View the Core Package Version

To view the version of the core package, use the following command:

[source,text,linenums]
----
$ anypoint-cli-v4 --version
----

The output shows the version of the installed core package as follows:

----
@mulesoft/anypoint-cli-v4/0.4.2 darwin-x64 node-v12.22.5
----

[[view-plugin-list]]
=== View the List of Plugins Installed

To verify a plugin installation and view the list of plugins you have installed, use the following command:

[source,text,linenums]
----
$ anypoint-cli-v4
----

The output shows the installed plugins under the `TOPICS` section. The following example shows that only the account plugin is installed. 

----
VERSION
  @mulesoft/anypoint-cli-v4/x.x.x linux-x64 node-v14.17.6
 
USAGE
  $ anypoint-cli-v4 [COMMAND]
 
TOPICS
  account  Show details of a business group. If "name" is omitted, defaults to the current session's business group
  plugins  list installed plugins
 
COMMANDS
  conf     manage configuration
  help     display help for anypoint-cli
  plugins  list installed plugins
----

[[view-all-version-info]]
=== View All Version Information

To see the list of installed plugins along with full version information, use the following command: 

[source,text,linenums]
----
$ anypoint-cli-v4 plugins
----

The output shows the version information as follows: 

----
$ anypoint-cli-v4 plugins
@mulesoft/anypoint-cli-account-plugin x.x.x
└─ @mulesoft/anypoint-cli-command x.x.x
└─ conf-cli 0.1.9
----

[[uninstall-plugin]]
== Uninstall a Plugin

You can selectively uninstall plugins. One reason you might want to do this is if you have installed several plugins and decide you want to uninstall all except the ones you are regularly using. 

To uninstall a plugin, use the following command:

[source,text,linenums]
----
$ anypoint-cli-v4 plugins:uninstall @mulesoft/anypoint-cli-<plugin-name>-plugin
----

For example:

The following command uninstalls the account plugin.

[source,text,linenums]
----
$ anypoint-cli-v4 plugins:uninstall @mulesoft/anypoint-cli-account-plugin
----

See <<plugin-list,List of Plugins>>.