= Install Anypoint CLI 4.x

Install Anypoint Platform CLI 4.x from npm to access command-line tools for Anypoint Platform and Anypoint Platform Private Cloud Edition (PCE). The installation process includes <<prereqs,installing prerequisite software>>, <<installation,installing the CLI package with default plugins>>, and optionally <<install-plugins,installing nondefault plugins>>. <<verify-installation,Verify the installation>> to ensure proper setup for automating platform operations and managing applications. CLI supports both cloud and on-premises deployments, enabling integration with CI/CD workflows and enterprise environments.

[[prereqs]]
== Before You Begin

The Anypoint CLI is built with Node.js and is installed by using npm, the package manager for the Node JavaScript platform.

Versions required are as follows:

* Node.js version 22.0.0 or later
* npm version 7 or later

To install the prerequisite software:

* Download and install Node.js and npm.
+
See the https://nodejs.org/en/download/[NodeJS download page].

Depending on the configuration of your system, you might need to log in using administrator credentials before you can successfully run the npm commands.

[[installation]]
== Install the Core Package and Default Plugins

Run the following command to install the Anypoint CLI core package and all default plugins. See <<plugin-list,List of Plugins>>.

[source,text,linenums]
----
npm install -g anypoint-cli-v4-public
----

[[install-plugins]]
== Install a Plugin Separately

After installing the Anypoint CLI 4.x core package, you can install nondefault plugins or new versions of default plugins as follows:

[source,text,linenums]
----
anypoint-cli-v4 plugins:install <plugin-name>
----

For example, to install the account plugin, use the following command:

[source,text,linenums]
----
anypoint-cli-v4 plugins:install anypoint-cli-account-plugin
----

[[plugin-list]]
=== List of Plugins

You can install the following plugins with Anypoint CLI:  

[%header,cols="35a,65a"]
|===
|Plugin |Description
| anypoint-cli-account-plugin | Account command topics
| anypoint-cli-agent-fabric-plugin | Agent Fabric command topics
| anypoint-cli-api-manager-plugin | API Manager command topics
| anypoint-cli-cloudhub-plugin | CloudHub and CloudHub 2.0 command topics
| anypoint-cli-datagraph-plugin | Anypoint DataGraph command topics
| anypoint-cli-dx-mule-plugin | DX Mule command topics
| anypoint-cli-exchange-plugin | Exchange command topics
| mulesoft-anypoint-cli-designcenter-plugin | Design Center command topics
| mulesoft-anypoint-cli-governance-plugin | API Governance command topics
| anypoint-cli-runtime-mgr-plugin | Runtime Manager command topics
| anypoint-cli-secrets-mgr-plugin | Secrets Manager command topics
|===

NOTE: The API Governance plugin npm package name is now `mulesoft-anypoint-cli-governance-plugin`. The old name `anypoint-cli-governance-plugin` is deprecated. If you use the old name, see <<migrate-governance-plugin>>.

[[migrate-governance-plugin]]
==== Migrate to the New Governance Plugin Package Name

To migrate to the new package name `mulesoft-anypoint-cli-governance-plugin`:

. In your `package.json` file, replace the `"anypoint-cli-governance-plugin": "1.0.x"` dependency with `"mulesoft-anypoint-cli-governance-plugin": "1.0.19"`.
. For oclif hosts, such as Anypoint CLI v4, update the entry in the `oclif.plugins` array from `"anypoint-cli-governance-plugin"` to `"mulesoft-anypoint-cli-governance-plugin"`.
. Run `npm install` to refresh your lockfile.
. Regenerate the oclif manifest and README by running `oclif manifest && oclif readme` if your host publishes one.


[[verify-installation]]
== Verify the Installation

After you install Anypoint CLI you can verify the installation using commands to:

* <<view-core-version>>
* <<view-plugin-list>>
* <<view-all-version-info>>

[[view-core-version]]
=== View the Core Package Version

To view the version of the core package:

[source,text,linenums]
----
anypoint-cli-v4 --version
----

The output shows the version of the installed core package as follows:

----
anypoint-cli-v4/1.x.x <OS-version> node-v16.x.x
----

[[view-plugin-list]]
=== View the List of Plugins Installed

To verify a plugin installation and view a list of all installed  plugins, use the following command:

[source,text,linenums]
----
anypoint-cli-v4
----

The output shows the installed plugins under the `TOPICS` section. The following example shows that only the account plugin is installed:

----
VERSION
  anypoint-cli-v4/x.x.x <OS-version> node-vx.x.x

USAGE
  $ anypoint-cli-v4 [COMMAND]

TOPICS
  account  Show details of a business group. If "name" is omitted, defaults to the current session's business group
  plugins  list installed plugins

COMMANDS
  help     display help for anypoint-cli
  plugins  list installed plugins
----

[[view-all-version-info]]
=== View All Version Information

To see the list of installed plugins along with full version information, use the following command: 

[source,text,linenums]
----
anypoint-cli-v4 plugins --core
----

The output shows the version information: 

----
$ anypoint-cli-v4 plugins --core
@oclif/plugin-help 5.1.15 (core)
@oclif/plugin-not-found 2.3.4 (core)
@oclif/plugin-plugins 2.1.2 (core)
@oclif/plugin-version 1.1.3 (core)
anypoint-cli-account-plugin 1.0.0 (core)
anypoint-cli-api-mgr-plugin 1.0.0 (core)
anypoint-cli-cloudhub-plugin 1.0.0 (core)
anypoint-cli-command 1.0.1 (core)
anypoint-cli-designcenter-plugin 1.0.2 (core)
anypoint-cli-exchange-plugin 1.0.0 (core)
└─conf-cli 0.1.9 (core)
anypoint-cli-runtime-mgr-plugin 1.0.0 (core)
anypoint-cli-v4 1.0.2 (core)

----

[[link-plugin]]
== Link a Local Plugin for Development

To link a local plugin directory into the CLI for development purposes:

[source,text,linenums]
----
anypoint-cli-v4 plugins:link <path>
----

For example, to link a plugin in the current directory:

[source,text,linenums]
----
anypoint-cli-v4 plugins:link .
----

NOTE: Installing a linked plugin overrides a user-installed or core plugin that has the same commands.

[[autocomplete]]
== Enable Shell Autocomplete

To display autocomplete installation instructions for your shell:

[source,text,linenums]
----
anypoint-cli-v4 autocomplete [bash|zsh|powershell]
----

For example, to set up autocomplete for Zsh:

[source,text,linenums]
----
anypoint-cli-v4 autocomplete zsh
----

To refresh the autocomplete cache after installing new plugins:

[source,text,linenums]
----
anypoint-cli-v4 autocomplete --refresh-cache
----

[[uninstall-plugin]]
== Uninstall a Plugin

Uninstall plugins if, for example, you want to reduce the number to only those you use regularly.  

To uninstall a plugin:

[source,text,linenums]
----
anypoint-cli-v4 plugins:uninstall anypoint-cli-<plugin-name>-plugin
----

For example, the following command uninstalls the account plugin:

[source,text,linenums]
----
anypoint-cli-v4 plugins:uninstall anypoint-cli-account-plugin
----

See <<plugin-list,List of Plugins>>.

[[uninstall-anypoint-cli]]
== Uninstall Anypoint CLI

You might want to uninstall Anypoint CLI from systems where it is no longer being used. 

To uninstall the Anypoint CLI:

[source,text,linenums]
----
npm uninstall -g anypoint-cli-v4-public
----