= General Use of Commands and Options

include::anypoint-cli::partial$intro.adoc[tag=usageintro]

include::anypoint-cli::partial$intro.adoc[tag=syntax]

== Optional Options

The Anypoint CLI has the following optional options:

[%header%autowidth.spread,cols="a,a"]
|===
|Option|Description
| `organization` | Your organization within Anypoint Platform

You can also pass this value using the environment variable `export ANYPOINT_ORG=<name>`.

| `environment` | Your Anypoint Platform environment

You can also pass this value using the environment variable `export ANYPOINT_ENV=<name>`.

| `host` | The host of your Anypoint Platform Installation +
This value defaults to `anypoint.mulesoft.com`. +

* If you are using Anypoint Platform PCE, pass the address where you are hosting the platform.
* If you are using Anypoint Platform EU Cloud, pass your EU control plane URL.

You can also pass this value using a dedicated environment variable `ANYPOINT_HOST=<name>`. For example, `ANYPOINT_HOST=my.anypoint.mulesoft.com`.

|===

[[overrides]]
== Override Order

You can use environment variables to define option values in Anypoint CLI. Following is the override order if you mix environment variable settings with explicit command line values:

* Environment variables override credentials file parameters.
* Command-line parameters override environment variables. 
* If you do not pass a command-line option, the default profile properties are used.
* If environment is not specified, the default is production.

[[session-timeout]]
== Session Timeout
Your Anypoint Platform session expires based on the *Default session timeout* configured in your Master Organization settings.

For information about Master Organization settings, see xref:access-management::organization.adoc#manage-root-organization-settings[Manage Root Organization Settings].

[[data-collection]]
== Anonymized Usage Data

To improve the Anypoint CLI experience, we gather anonymized usage data. You can opt out by setting `collectMetrics` to false in the `credentials` file.