= General Use of Commands and Options

include::anypoint-cli::partial$intro.adoc[tag=usageintro]

include::anypoint-cli::partial$intro.adoc[tag=syntax]

== Optional Arguments

The Anypoint CLI has the following optional arguments:

[%header%autowidth.spread,cols="a,a"]
|===
|Parameter |Description
| `organization` | Your organization within Anypoint Platform

You can also pass this value using the environment variable `export ANYPOINT_ORG=<name>`.

| `environment` | Your Anypoint Platform environment

You can also pass this value using the environment variable `export ANYPOINT_ENV=<name>`.

| `host` | The host of your Anypoint Platform Installation +
By default, this value points to `\https://anypoint.mulesoft.com`. +

* If you are using Anypoint Platform PCE, pass the address where you are hosting the platform.
* If you are using Anypoint Platform EU Cloud, pass your EU control plane URL.

You can also pass this value using a dedicated environment variable `ANYPOINT_HOST=<name>`.

|===

[[general]]
== General Functionality

Anypoint CLI provides the following general functionality. 

[[overrides]]
=== Override Order

You can use:environment variables to define parameter values in Anypoint CLI. Following is the override order if you mix environment variable settings with explicit command line values:

* Environment variables override credentials file parameters and command-line parameters override environment variables. +
If you don't pass a command-line parameter, the default profile properties are used.
* If not specified, the default environment is production.


[[session-timeout]]
=== Session Timeout
Your Anypoint Platform session expires based on the *Default session timeout* configured in your Master Organization settings.

For information about Master Organization settings, see xref:access-management::organization.adoc#manage-root-organization-settings[Manage Root Organization Settings].

[[autocomplete]]
=== Command Autocompletion

The Anypoint CLI works with autocomplete.

You can start typing the name of the command or parameter and press Tab for autocomplete or press Tab+Tab for a list of options.

[[data-collection]]
=== Anonymized Usage Data

To improve the Anypoint CLI experience, we gather anonymized usage data. You can opt out by setting `collectMetrics` to false in the `credentials` file.

== See Also

* xref:auth.adoc[Authentication Methods]
* xref:proxy.adoc[Use Anypoint CLI Through a Network Proxy]
* xref:anypoint-platform-cli-commands.adoc[List of Commands]
* xref:diff-earlier-ver.adoc[Differences from Earlier Versions]