= Using Anypoint CLI with a Network Proxy

Anypoint CLI can be run through a network proxy to add a layer of security. To use the Anypoint CLI with a proxy server, configure the `HTTP_PROXY` and `HTTPS_PROXY` environment variables with the hostname or IP addresses of your proxy servers as shown in the following sections.

== Configure a Proxy Server Without Authentication

Depending on your operating system, use the following commands:

* Linux, macOS, or Unix
+
--
`$ export HTTP_PROXY=http://__proxy-server__:80`

`$ export HTTPS_PROXY=https://__proxy-server__:443`
--

* Windows
+
--
`> set HTTP_PROXY=http://__proxy-server__:80`

`> set HTTPS_PROXY=https//__proxy-server__:443`
--

== Configure a Proxy Server With Authentication

If the proxy server requires authentication, depending on your operating system, use these commands:

* Linux, macOS, or Unix
+
--
`$ export HTTP_PROXY=http://__username__:__password__@__proxy-server__:80`

`$ export HTTPS_PROXY=https://__username__:__password__@__proxy-server__:443`
--

* Windows
+
--
`> set HTTP_PROXY=http://__username__:__password__@__proxy-server__:80`

`> set HTTPS_PROXY=https://__username__:__password__@__proxy-server__:443`
--


