
= Anypoint Platform Account

// tag::summary[]

[%header,cols="35a,65a"]
|===
|Command |Description
|xref:account.adoc#account-user-describe[account:user:describe]| Show account details
|xref:account.adoc#account-business-group-list[account:business-group:list]| Lists business groups
|xref:account.adoc#account-business-group-describe[account:business-group:describe]| Show details of a business group
|xref:account.adoc#account-environment-list[account:environment:list]| Lists environments
|xref:account.adoc#account-environment-create[account:environment:create]| Create new environment
|xref:account.adoc#account-environment-delete[account:environment:delete]| Delete an environment
|xref:account.adoc#account-environment-describe[account:environment:describe]| Shows details of an environment
|===

// end::summary[]


// tag::commands[]

[[account-user-describe]]
== account:user:describe

----
> account:user:describe  [options]
----

This command simply returns the information for your account. This includes your username, your full name, your email address, and the creation date of your account. +
This command does not take any options, except for the default ones: `--help`, `-f`/`--fields` and `-o`/`--output`

[[account-business-group-list]]
== account:business-group:list

----
> account:business-group:list [options]
----

This command displays all xref:access-management::business-groups.adoc[business groups]. It returns the name of the business group, the type ('Master' or 'Business unit'), and the ID.

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

[[account-business-group-describe]]
== account:business-group:describe

----
> account:business-group:describe  [options] <name>
----

This command displays information on the business group you pass in `<name>`. +
If `<name>` is not specified, the command describes the business group on the current session.

[NOTE]
--
If your business group or organization name contains spaces, you need to enclose its name between `"` characters.

----
> account:business-group:describe "QA Organization"
----
--

It returns data such as the owner, the type, subscription information, the entitlements of the group and in which environment is running.

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

[[account-environment-list]]
== account:environment:list

----
> account:environment:list [options]
----
This command lists all your environments in Anypoint Platform. It returns your environment name, Id and whether it's sandboxed or not. +
This command does not take any options, except for the default ones: `--help`, `-f`/`--fields` and `-o`/`--output`

[[account-environment-create]]
== account:environment:create

----
> account:environment:create [options] <name>
----
This command creates a new environment using the name you set in `<name>`. +
Besides the default `--help`, `-f`/`--fields` and `-o`/`--output` options, this command also takes the `--type` option. Use the `--type` option to specify the environment type. +
Supported values for environment types are:

* `design`
* `production`
* `sandbox`

If no type is specified, the command creates a production environment.

[[account-environment-delete]]
== account:environment:delete

----
> account:environment:delete  [options] <name>
----
This command deletes the environment specified in `<name>` +

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

[[account-environment-describe]]
== account:environment:describe

----
> account:environment:describe [options] <name>
----

This command returns information about the environment specified in `<name>` +
If no `<name>` is provided, this command returns information about the current session's environment.

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

// end::commands[]
