
= Anypoint Platform Account

// tag::summary[]

[%header,cols="35a,65a"]
|===
|Command |Description
|xref:account.adoc#account-user-describe[account:user:describe]| Show account details
|xref:account.adoc#account-business-group-list[account:business-group:list]| Lists business groups
|xref:account.adoc#account-business-group-describe[account:business-group:describe]| Show details of a business group
|xref:account.adoc#account-environment-list[account:environment:list]| Lists environments
|xref:account.adoc#account-environment-create[account:environment:create]| Create new environment
|xref:account.adoc#account-environment-delete[account:environment:delete]| Delete an environment
|xref:account.adoc#account-environment-describe[account:environment:describe]| Shows details of an environment
|===

// end::summary[]


// tag::commands[]

[[account-user-describe]]
== account:user:describe

----
> account:user:describe  [flags]
----

Returns your account information, including your username, your full name, your email address, and the creation date of your account. 

Use the `--output` flag to specify the response format. Supported values are `table` (default) and `json`.

This command accepts the default flag `--help`.

[[account-business-group-list]]
== account:business-group:list

----
> account:business-group:list [flags]
----

Displays all xref:access-management::business-groups.adoc[business groups]. It returns the name of the business group, the type ('Master' or 'Business unit'), and the ID.

Use the `--output` flag to specify the response format. Supported values are `table` (default) and `json`.

This command accepts the default flag `--help`.

[[account-business-group-describe]]
== account:business-group:describe

----
> account:business-group:describe  [flags] <identifier>
----

This command displays information on the business group you pass in `<organizationID>`. +
If `<organizationID>` is not specified, the command describes the business group on the current session.

[NOTE]
--
If your business group or organization name contains spaces, enclose its name between `"` characters.

----
> account:business-group:describe "QA Organization"
----
--

Returns the business group owner, type, subscription information, the entitlements of the group and in which environment is running.

Use the `--output` flag to specify the response format. Supported values are `table` (default) and `json`.

This command accepts the default flag `--help`.

[[account-environment-list]]
== account:environment:list

----
> account:environment:list [flags]
----
This command lists all your environments in Anypoint Platform. It returns your environment name, Id and whether it's sandboxed or not. 

Use the `--output` flag to specify the response format. Supported values are `table` (default) and `json`.

This command accepts the default flag `--help`.

[[account-environment-create]]
== account:environment:create

----
> account:environment:create [flags] <name>
----
This command creates a new environment using the name you set in `<name>`. +
 Use the `--type` flag to specify the environment type. +
Supported values for environment types are:

* `design`
* `production`
* `sandbox`

If no type is specified, the command creates a sandbox environment.

Use the `--output` flag to specify the response format. Supported values are `table` (default) and `json`.

This command accepts the default flag `--help`.

[[account-environment-delete]]
== account:environment:delete

----
> account:environment:delete  [flags] <name>
----
This command deletes the environment specified in `<name>` +

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

This command accepts only the default flag `--help`.

[[account-environment-describe]]
== account:environment:describe

----
> account:environment:describe [flags] <name>
----

This command returns information about the environment specified in `<name>` +
If no `<name>` is provided, this command returns information about the current session's environment.

Use the `--output` flag to specify the response format. Supported values are `table` (default) and `json`

This command accepts the default flag `--help`.

// end::commands[]
