= API Governance


// tag::summary[]

|===
|Command |Description
| xref:api-governance.adoc#governance-api-validate[governance api validate] | Validates an API definition against a specified governance ruleset
| xref:api-governance.adoc#governance-document[governance document] | Creates the documentation file for a governance ruleset definition
| xref:api-governance.adoc#governance-profile-create[governance profile create] | Creates a governance profile
| xref:api-governance.adoc#governance-profile-delete[governance profile delete] | Deletes a governance profile
| xref:api-governance.adoc#governance-profile-info[governance profile info] | Lists information for a specific governance profile ID
| xref:api-governance.adoc#governance-profile-list[governance profile list] | Lists all governance profiles for an organization
| xref:api-governance.adoc#governance-profile-update[governance profile update] | Updates a governance profile
| xref:api-governance.adoc#governance-ruleset-validate[governance ruleset validate] | Validates a governance ruleset definition's format
|===

// end::summary[]

// tag::governance-api-validate[]

[[governance-api-validate]]
== governance api validate

`> governance api validate [options] <api-definition>`

This command validates the API definition passed in `api-definition` against specified rulesets. `api-definition` can be a ZIP file or a project folder. If the API project specified includes the 'exchange.json' file that defines dependencies, the command downloads all dependencies and validates against the rulesets in the project. If the ZIP file does not include ruleset dependency information, you must also use the `--ruleset` option and specify the ruleset YAML files against which you want to validate, separated by commas. 

Besides the default options `--help`, `-f/--fields` and `-o/--output` options, this command also takes:

[cols="1,1"]
|===
|Option |Description

|--rulesets <ruleset-yaml-file1>,<ruleset-yaml-file2>,...
|The `rulesets` option is followed by a comma-separated list of ruleset YAML files. If the API ZIP file contains a ruleset that is a duplicate of a ruleset included in the project dependencies, both will be validated.
|===

*Example commands:*

----
anypoint-cli governance api validate ~/Downloads/order-api-1.0.0-raml.zip

anypoint-cli governance api validate --ruleset /MyRulesets/ruleset1.yaml,/MyRulesets/ruleset2.yaml  ~/Downloads/order-api-1.0.0-raml.zip
----

*Example output:*

For a specification that is conformant to the ruleset:

----
 Spec conforms with Ruleset
----

For a specification that is nonconformant to the ruleset:

----
 Ruleset /path/Downloads/ruleset.yaml
 Spec /path/Downloads/order-api-1.0.0-raml.zip
 Spec does not conform with Ruleset
 [.. full report shown here..]
----

// end::governance-api-validate[]

// tag::governance-document[]

[[governance-document]]
== governance document

`> governance document [options] <ruleset> <doc-file>`

This command creates the documentation for the API Governance ruleset definition ZIP file specified in `ruleset`. It puts the documentation in the `doc-file` ZIP file for you to upload and publish to Exchange. 

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

*Example command:*

----
anypoint-cli governance document ~/temp/ruleset.yaml ~/temp/ruleset.doc.zip
----

*Example output:*

----
 validation name [ 'scalar-parameters' ]
 Saving to /Users/janedoe/temp/prof-1.doc.zip
----

// end::governance-document[]

// tag::governance-profile-create[]

[[governance-profile-create]]
== governance profile create

`> governance profile create [options] <profile-name> <ruleset-asset-identifiers>`

This command creates a governance profile using a string value for the new governance profile name specified in `profile-name`. You must include `ruleset-asset-identifiers`, a list with the group ID, asset ID, and version (gav), which is the unique asset identifiers for each ruleset. Use a comma separated list formatted as follows: `<group_id>/<asset_id>/<version>,<group_id>/<asset_id>/<version>` 

To get the ruleset asset identifiers:

* If you are using the CLI, run the `anypoint-cli exchange asset list` command. 
* If you are using the web UI, select the ruleset asset in Exchange and then copy the group ID and asset ID from the URL. 

Besides the default options `--help`, `-f/--fields` and `-o/--output` options, this command also takes:

[cols="1,1"]
|===
|Option |Description

|--tags <tags>
|The `tags` option is followed by a comma separated list of tags to be applied to the new governance profile, formatted as follows: `tag1,tag2,tag3`

|--description <description>
|The `description` option is followed by a string that is the new governance profile's description.
|===

*Example command:*

----
anypoint-cli governance profile create "OAS Best Practices" 68ef9520-24e9-4cf2-b2f5-620025690913/open-api-best-practices/1.0.1 --tags best --description "Profile for OAS Best Practices"
----

*Example output:*

----
 Profile Added
 Id         	4f98e59d-8efb-420f-ac95-9cd0af15bd45                                    
 Name       	OAS Best Practices                                                        
 Description	Profile for OAS Best Practices                                
 Rulesets   	gav://68ef9520-24e9-4cf2-b2f5-620025690913/open-api-best-practices/1.0.1
 Filter     	tag:best    
----

// end::governance-profile-create[]

// tag::governance-profile-delete[]

[[governance-profile-delete]]
== governance profile delete

`> governance profile delete [options] <profile-id>`

This command deletes a specific governance profile specified by `profile-id`. To get this ID, run the `governance profile info` or `governance profile list` command.

The `governance profile delete` command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

*Example command:*

----
anypoint-cli governance profile delete 8ffd463f-86b2-4132-afc6-44d179209362
----

*Example output:*

----
 Profile with id 8ffd463f-86b2-4132-afc6-44d179209362 removed
----

// end::governance-profile-delete[]

// tag::governance-profile-info[]

[[governance-profile-info]]
== governance profile info

`> governance profile info [options] <profile-id>`

This command lists all information for a governance profile ID.

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

*Example command:*

----
anypoint-cli governance profile info 8ffd463f-86b2-4132-afc6-44d179209362
----

*Example output:*

----
Id         	19fb211b-8775-43cc-865a-46228921d6ed                                                                                                    
Name       	Best Practices                                                                                                                          
Description	Best Practices Profile                                                                                                                  
Rulesets   	gav://3280b56c-e887-40f9-a9aa-db1118f719d5/best-practices/1.0.0 gav://68ef9520-24e9-4cf2-b2f5-620025690913/anypoint-best-practices/1.0.0
Filter     	tag:best 
----

// end::governance-profile-info[]

// tag::governance-profile-list[]

[[governance-profile-list]]
== governance profile list

`> governance profile list [options] `

This command lists information for all governance profiles for an organization. You need this information when updating a governance profile.

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

*Example output:*

----
 Profile Name  	     Profile Id                          
	
 OAS Best Practices	 4f98e59d-8efb-420f-ac95-9cd0af15bd45

----
// end::governance-profile-list[]

// tag::governance-profile-update[]

[[governance-profile-update]]
== governance profile update

`> governance profile update [options] <profile-id>`

This command updates the governance profile specified in `profile-id`. To get this ID, run the `governance profile info` or `governance profile list` command.

You can update the governance profile's
governance name, rulesets, tags, and description. 

Besides the default options `--help`, `-f/--fields` and `-o/--output` options, this command also takes:

[cols="1,1"]
|===
|Option |Description

|--profile-name <profile-name>
|The `profile-name` argument is followed by a string that is the new governance profile name.

|--ruleset-gavs <ruleset-gavs>
|The `ruleset-gavs` argument is a list with the group ID, asset ID, and version for each ruleset, formatted as follows: `<group_id>/<asset_id>/<version>,<group_id>/<asset_id>/<version>` 

These are the asset's identifiers.

|--tags <tags>
|The `tags` argument is followed by a comma separated list of tags formatted as follows: `tag1,tag2,tag3`.

|--description <description>
|The `description` argument is followed by a string that is the new governance profile description.
|===

*Example command:*

----
anypoint-cli governance profile update 51f9f94c-fb0c-43d4-9895-22c9e64f1537 --profile-name "New Name"
----

*Example output:*

----
 Profile updated 51f9f94c-fb0c-43d4-9895-22c9e64f1537
----

// end::governance-profile-update[]

// tag::governance-ruleset-validate[]

[[governance-ruleset-validate]]
== governance ruleset validate

`> governance ruleset validate [options] <rulesets>`

This command validates the ruleset definitions passed using the `rulesets` parameter. You can pass one of the following as the `rulesets` parameter:

* A ruleset definition YAML file  
* A ZIP file with one or more ruleset definitions
* A folder with one or more ruleset definitions

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

*Example commands:*

----
anypoint-cli governance ruleset validate ~/temp/myruleset.yaml

anypoint-cli governance ruleset validate ~/temp/myrulesets.zip

anypoint-cli governance ruleset validate ~/temp/myfolder

anypoint-cli governance ruleset validate ~/temp/myfolder exchange.json myruleset.yaml
----

*Example output for a valid ruleset:*

----
 Ruleset conforms with Dialect
----

*Example output for a nonvalid ruleset:*

----
Ruleset does not conform with Dialect
ModelId: file:///Users/janedoe/temp/prof-1-bad.yaml
Profile: Validation Profile 1.0
Conforms: false
Number of results: 1

Level: Violation

- Constraint: http://a.ml/amf/default_document#/declarations/profileNode_profile_required_validation
  Message: Property 'profile' is mandatory
  Severity: Violation
  Target: file:///Users/janedoe/temp/prof-1-bad.yaml#/encodes
  Property: http://schema.org/name
  Range: [(3,0)-(11,19)]
  Location: file:///Users/janedoe/temp/prof-1-bad.yaml
----

// end::governance-ruleset-validate[]