= API Governance


// tag::summary[]

|===
|Command |Description
| xref:api-governance.adoc#governance-api-validate[governance api validate] | Validates an API definition against a specified governance ruleset
| xref:api-governance.adoc#governance-document[governance document] | Creates the documentation file for a governance ruleset definition
| xref:api-governance.adoc#governance-profile-create[governance profile create] | Creates a governance profile
| xref:api-governance.adoc#governance-profile-delete[governance profile delete] | Deletes a governance profile
| xref:api-governance.adoc#governance-profile-info[governance profile info] | Lists information for a specific governance profile ID
| xref:api-governance.adoc#governance-profile-list[governance profile list] | Lists all governance profiles for an organization
| xref:api-governance.adoc#governance-profile-update[governance profile update] | Updates a governance profile
| xref:api-governance.adoc#governance-ruleset-validate[governance ruleset validate] | Validates a governance ruleset definition's format
|===

// end::summary[]

// tag::governance-api-validate[]

[[governance-api-validate]]
== governance api validate

`> governance api validate [options] <api-definition>`

This command validates the API definition passed in `api-definition` against specified rulesets. 

You can specify `api-definition` as an API project ZIP file or folder and specify rulesets against which to validate using one or more of the following:

* To use an existing `exchange.json` file that defines your API project's ruleset dependencies, ensure that it is included in the folder or ZIP file that you specify in `api-definition`. If the `exchange.json` file is present, the command downloads all dependencies and validates against the rulesets in the project. 

* To validate directly against rulesets published in Exchange, use the `--remote-rulesets` option. 

* To validate against local rulesets, use the `--rulesets` option.

NOTE: Duplicate rulesets are not detected, so if you use more than one of the preceding ways of identifying rulesets in the same command execution, some rulesets may be validated multiple times.

Besides the default options `--help`, `-f/--fields` and `-o/--output` options, this command also takes:

[cols="1,1"]
|===
|Option |Description

|--rulesets <ruleset-yaml-file1>,<ruleset-yaml-file2>,...
|The `rulesets` option is followed by a comma-separated list of ruleset YAML files. 
|--remote-rulesets <ruleset-asset-identifier>,<ruleset-asset-identifier>,...
|The `remote-rulesets` option is followed by a comma-separated list of ruleset asset identifiers, each of which is the group ID, asset ID, and version (GAV) that uniquely identifies each ruleset. For example: `<group_id>/<asset_id>/<version>,<group_id>/<asset_id>/<version>`

See <<exchange-asset-identifiers>>.

|===

*Example commands:*

[source,copy]
----
anypoint-cli governance api validate ~/Downloads/order-api-1.0.0-raml.zip

anypoint-cli governance api validate ~/Downloads/order-api-1.0.0-raml

anypoint-cli governance api validate --rulesets /MyRulesets/ruleset1.yaml,/MyRulesets/ruleset2.yaml  ~/Downloads/order-api-1.0.0-raml.zip

anypoint-cli governance api validate --remote-rulesets 68ef9520-24e9-4cf2-b2f5-620025690913/open-api-best-practices/1.0.1  ~/Downloads/order-api-1.0.0-raml.zip
----

*Example output:*

For a specification that is conformant to the ruleset:

----
 Spec conforms with Ruleset
----

For a specification that is nonconformant to the ruleset:

----
Conforms: false 
Number of results: 3 <1>

Functional Validations 
----------------------

Constraint: http://a.ml/vocabularies/amf/core#declaration-not-found
Severity: Violation
Message: not supported scalar for documentation
Target: null
Range: [(6,3)-(6,3)]
Location: file:///Users/myuser/Downloads/order-api-1.0.0-raml/order-api-1.0.0-raml

Conformance Validations <2>
-----------------------

Constraint: file:///exchange_modules/68ef9520-24e9-4cf2-b2f5-620025690913/anypoint-best-practices/1.0.0/ruleset.yaml#/encodes/validations/api-must-have-documentation <3>
Severity: Warning <4>
Message: Provide the documentation for the API. <5>
Target: amf://id#2 <6>
Range: [(2,0)-(6,4)] <7>
Location: file:///Users/myuser/Downloads/order-api-1.0.0-raml/order-api-1.0.0-raml <8>

Constraint: file:///exchange_modules/8a840abd-e63a-4f8b-87ab-24052eda2017/best-practices-ruleset/1.0.0/bestpractices.yaml#/encodes/validations/api-must-have-documentation
Severity: Violation
Message: Provide the documentation for the API
Target: amf://id#2
Range: [(2,0)-(6,4)]
Location: file:///Users/myuser/Downloads/order-api-1.0.0-raml/order-api-1.0.0-raml
----

<1> Total of functional and conformance validation issues found
<2> Conformance issues section 
<3> Ruleset and rule to which this set of issues applies 
<4> Severity level for the issue
<5> Description of the issue
<6> AMF model node ID; for information on the AMF model, see xref:api-governance::create-custom-rulesets.adoc#[Creating Custom Governance Rulesets] 
<7> Beginning line number and column and end line number and column in the API definition where the issue occurs, where column is the offset from the beginning of the line and numbering for the offset starts at 0
<8> The file in which the issue occurs, either the main file or one of its dependencies

// end::governance-api-validate[]

// tag::governance-document[]

[[governance-document]]
== governance document

`> governance document [options] <ruleset> <doc-file>`

This command creates the documentation for the API Governance ruleset definition ZIP file specified in `ruleset`. It puts the documentation in the `doc-file` ZIP file for you to upload and publish to Exchange. 

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

*Example command:*

[source,copy]
----
anypoint-cli governance document ~/temp/ruleset.yaml ~/temp/ruleset.doc.zip
----

*Example output:*

----
 validation name [ 'scalar-parameters' ]
 Saving to /Users/janedoe/temp/prof-1.doc.zip
----

// end::governance-document[]

// tag::governance-profile-create[]

[[governance-profile-create]]
== governance profile create

`> governance profile create [options] <profile-name> <ruleset-asset-identifiers>`

This command creates a governance profile using a string value for the new governance profile name specified in `profile-name`. 

You must include `ruleset-asset-identifiers`, a comma-separated list of ruleset asset identifiers, each of which is the group ID, asset ID, and version (GAV) that uniquely identifies each ruleset. For example: `<group_id>/<asset_id>/<version>,<group_id>/<asset_id>/<version>`

See <<exchange-asset-identifiers>>.

Besides the default options `--help`, `-f/--fields` and `-o/--output` options, this command also takes:

[cols="1,1"]
|===
|Option |Description

|--tags <tags>
|The `tags` option is followed by a comma separated list of tags to be applied to the new governance profile, formatted as follows: `tag1,tag2,tag3`

|--description <description>
|The `description` option is followed by a string that is the new governance profile's description.
|===

*Example command:*

[source,copy]
----
anypoint-cli governance profile create "OAS Best Practices" 68ef9520-24e9-4cf2-b2f5-620025690913/open-api-best-practices/1.0.1 --tags best --description "Profile for OAS Best Practices"
----

*Example output:*

----
 Profile Added
 Id         	4f98e59d-8efb-420f-ac95-9cd0af15bd45                                    
 Name       	OAS Best Practices                                                        
 Description	Profile for OAS Best Practices                                
 Rulesets   	gav://68ef9520-24e9-4cf2-b2f5-620025690913/open-api-best-practices/1.0.1
 Filter     	tag:best    
----

// end::governance-profile-create[]

// tag::governance-profile-delete[]

[[governance-profile-delete]]
== governance profile delete

`> governance profile delete [options] <profile-id>`

This command deletes a specific governance profile specified by `profile-id`. To get this ID, run the `governance profile info` or `governance profile list` command.

The `governance profile delete` command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

*Example command:*

[source,copy]
----
anypoint-cli governance profile delete 8ffd463f-86b2-4132-afc6-44d179209362
----

*Example output:*

----
 Profile with id 8ffd463f-86b2-4132-afc6-44d179209362 removed
----

// end::governance-profile-delete[]

// tag::governance-profile-info[]

[[governance-profile-info]]
== governance profile info

`> governance profile info [options] <profile-id>`

This command lists all information for a governance profile ID.

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

*Example command:*

[source,copy]
----
anypoint-cli governance profile info 8ffd463f-86b2-4132-afc6-44d179209362
----

*Example output:*

----
Id         	19fb211b-8775-43cc-865a-46228921d6ed                                                                                                    
Name       	Best Practices                                                                                                                          
Description	Best Practices Profile                                                                                                                  
Rulesets   	gav://3280b56c-e887-40f9-a9aa-db1118f719d5/best-practices/1.0.0 gav://68ef9520-24e9-4cf2-b2f5-620025690913/anypoint-best-practices/1.0.0
Filter     	tag:best 
----

// end::governance-profile-info[]

// tag::governance-profile-list[]

[[governance-profile-list]]
== governance profile list

`> governance profile list [options]`

This command lists information for all governance profiles for an organization. You need this information when updating a governance profile.

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

*Example command:*

[source,copy]
----
anypoint-cli governance profile list
----

*Example output:*

----
 Profile Name  	     Profile Id                          
	
 OAS Best Practices	 4f98e59d-8efb-420f-ac95-9cd0af15bd45

----
// end::governance-profile-list[]

// tag::governance-profile-update[]

[[governance-profile-update]]
== governance profile update

`> governance profile update [options] <profile-id>`

This command updates the governance profile specified in `profile-id`. To get this ID, run the `governance profile info` or `governance profile list` command.

You can update the governance profile's
governance name, rulesets, tags, and description. 

Besides the default options `--help`, `-f/--fields` and `-o/--output` options, this command also takes:

[cols="1,1"]
|===
|Option |Description

|--profile-name <profile-name>
|The `profile-name` argument is followed by a string that is the new governance profile name.

|--ruleset-gavs <ruleset-gavs>
|The `ruleset-gavs` argument is a list with the group ID, asset ID, and version for each ruleset, formatted as follows: `<group_id>/<asset_id>/<version>,<group_id>/<asset_id>/<version>` 

These are the asset's identifiers. See <<exchange-asset-identifiers>>.

|--tags <tags>
|The `tags` argument is followed by a comma separated list of tags formatted as follows: `tag1,tag2,tag3`.

|--description <description>
|The `description` argument is followed by a string that is the new governance profile description.
|===

*Example command:*

[source,copy]
----
anypoint-cli governance profile update 51f9f94c-fb0c-43d4-9895-22c9e64f1537 --profile-name "New Name"
----

*Example output:*

----
 Profile updated 51f9f94c-fb0c-43d4-9895-22c9e64f1537
----

// end::governance-profile-update[]

// tag::governance-ruleset-validate[]

[[governance-ruleset-validate]]
== governance ruleset validate

`> governance ruleset validate [options] <governance-ruleset>`

This command validates the ruleset definitions passed using the `governance-ruleset` parameter. You can pass one of the following as the `governance-ruleset` parameter:

* A ruleset definition YAML file  
* A ZIP file that contains an API project with an `exchange.json` file that specifies the ruleset as the main file
* A folder that contains an API project with an `exchange.json` file that specifies the ruleset as the main file

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

*Example commands:*

[source,copy]
----
anypoint-cli governance ruleset validate ~/temp/myruleset.yaml

anypoint-cli governance ruleset validate ~/temp/myruleset.zip

anypoint-cli governance ruleset validate ~/temp/myrulesetfolder

----

*Example output for a valid ruleset:*

----
 Ruleset conforms with Dialect
----

*Example output for a nonvalid ruleset:*

----
Ruleset does not conform with Dialect
ModelId: file:///Users/janedoe/temp/prof-1-bad.yaml
Profile: Validation Profile 1.0
Conforms: false
Number of results: 1

Level: Violation

- Constraint: http://a.ml/amf/default_document#/declarations/profileNode_profile_required_validation
  Message: Property 'profile' is mandatory
  Severity: Violation
  Target: file:///Users/janedoe/temp/prof-1-bad.yaml#/encodes
  Property: http://schema.org/name
  Range: [(3,0)-(11,19)]
  Location: file:///Users/janedoe/temp/prof-1-bad.yaml
----

// end::governance-ruleset-validate[]

// tag::exchange-asset-identifier[]

[[exchange-asset-identifiers]]
=== Get Exchange Asset Identifiers (GAVs)

To get the GAVs for Exchange assets:

* If you are using the CLI, run the `anypoint-cli exchange asset list` command. 
* If you are using the web UI, select the asset in Exchange and then copy the group ID and asset ID from the URL. 

// end::exchange-asset-identifier[]