= API Governance


// tag::summary[]

|===
|Command |Description
| xref:api-governance.adoc#governance-api-evaluate[governance api evaluate] | Evaluates an API project to determine which rulesets would be applied to this API for given filters
| xref:api-governance.adoc#governance-api-inspect[governance api inspect] | Inspects an API definition to determine the API type
| xref:api-governance.adoc#governance-api-validate[governance api validate] | Validates an API definition against a specified governance ruleset
| xref:api-governance.adoc#governance-document[governance document] | Creates the documentation file for a governance ruleset definition
| xref:api-governance.adoc#governance-profile-create[governance profile create] | Creates a governance profile
| xref:api-governance.adoc#governance-profile-delete[governance profile delete] | Deletes a governance profile
| xref:api-governance.adoc#governance-profile-info[governance profile info] | Lists information for a specific governance profile ID
| xref:api-governance.adoc#governance-profile-list[governance profile list] | Lists all governance profiles for an organization
| xref:api-governance.adoc#governance-profile-update[governance profile update] | Updates a governance profile
| xref:api-governance.adoc#governance-ruleset-clone[governance ruleset clone] | Clones a governance ruleset and applies specified updates to rules
| xref:api-governance.adoc#governance-ruleset-info[governance ruleset info] | Lists ruleset rules
| xref:api-governance.adoc#governance-ruleset-init[governance ruleset init] | Initializes a governance ruleset definition based on a data schema
| xref:api-governance.adoc#governance-ruleset-validate[governance ruleset validate] | Validates a governance ruleset definition's format
|===

// end::summary[]

// tag::governance-api-evaluate[]

[[governance-api-evaluate]]
== governance api evaluate

`> governance api evaluate [options]`

This command evaluates on filters such as API type, tags, and categories to determine the rulesets that would be applied to your APIs for those filters. This gives developers a way through CLI to determine the rulesets that their APIs pass or fail for the same filters a governance administrator might set in an API Governance profile. 

Besides the default options `--help`, `-f/--fields` and `-o/--output` options, this command also takes:

[cols="1,1"]
|===
|Option |Description

|--api=<api>
|The API definition against which you want to evaluate.
|--criteria=<filtertype:filtervalue>,<filtertype:filtervalue>
|A list of filters against which you want to evaluate. They are separated by commas, where each filter has a type and value in the format filterType:filterValue. Available filters include category, tag, and scope (the targeted API types). Example: tag:tag1,category:category1:value,category:category2:value2,scope:async-api,scope:rest-api
|===

NOTE: This command must be run with either the `criteria` or the `api` option.  

*Example commands:*

[source,copy]
----
anypoint-cli governance api evaluate --criteria=tag:best,category:API Type:Experience API,scope:rest-api

anypoint-cli governance api evaluate --api ~/Downloads/order-api-1.0.0-raml.zip
----

*Example output:*

----
Ruleset GAV                                                       
68ef9520-24e9-4cf2-b2f5-620025690913/anypoint-best-practices/1.0.0
8a840abd-e63a-4f8b-87ab-24052eda2017/best-practices-ruleset/1.0.0 
68ef9520-24e9-4cf2-b2f5-620025690913/required-examples/1.0.0 
----

// end::governance-api-evaluate[]

// tag::governance-api-inspect[]

[[governance-api-inspect]]
== governance api inspect

`> governance api inspect [options] <api-definition>`

This command inspects the API definition passed in `api-definition` to determine the API type. 

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

*Example command:*

[source,copy]
----
anypoint-cli governance api inspect ~/Downloads/order-api-1.0.0-raml.zip

----

*Example output:*

----
 xxx
----

// end::governance-api-inspect[]

// tag::governance-api-validate[]

[[governance-api-validate]]
== governance api validate

`> governance api validate [options] <api-definition>`

This command validates the API definition passed in `api-definition` against specified rulesets. 

You can specify `api-definition` as an API project ZIP file or folder and specify rulesets against which to validate using one or more of the following:

* To use an existing `exchange.json` file that defines your API project's ruleset dependencies, ensure that it is included in the folder or ZIP file that you specify in `api-definition`. If the `exchange.json` file is present, the command downloads all dependencies and validates against the rulesets in the project. 

* To validate directly against rulesets published in Exchange, use the `--remote-rulesets` option. 

* To validate against local rulesets, use the `--rulesets` option.

NOTE: Duplicate rulesets are not detected, so if you use more than one of the preceding ways of identifying rulesets in the same command execution, some rulesets may be validated multiple times.

Besides the default options `--help`, `-f/--fields` and `-o/--output` options, this command also takes:

[cols="1,1"]
|===
|Option |Description

|--rulesets <ruleset-yaml-file1>,<ruleset-yaml-file2>,...
|The `rulesets` option is followed by a comma-separated list of ruleset YAML files. 
|--remote-rulesets <ruleset-asset-identifier>,<ruleset-asset-identifier>,...
|The `remote-rulesets` option is followed by a comma-separated list of ruleset asset identifiers, each of which is the group ID, asset ID, and version (GAV) that uniquely identifies each ruleset. For example: `<group_id>/<asset_id>/<version>,<group_id>/<asset_id>/<version>`

See <<exchange-asset-identifiers>>.

|===

*Example commands:*

[source,copy]
----
anypoint-cli governance api validate ~/Downloads/order-api-1.0.0-raml.zip

anypoint-cli governance api validate ~/Downloads/order-api-1.0.0-raml

anypoint-cli governance api validate --rulesets /MyRulesets/ruleset1.yaml,/MyRulesets/ruleset2.yaml  ~/Downloads/order-api-1.0.0-raml.zip

anypoint-cli governance api validate --remote-rulesets 68ef9520-24e9-4cf2-b2f5-620025690913/open-api-best-practices/1.0.1  ~/Downloads/order-api-1.0.0-raml.zip
----

*Example output:*

For a definition that is conformant to the ruleset:

----
 Spec conforms with Ruleset
----

For a definition that is nonconformant to the ruleset:

----
Conforms: false 
Number of results: 3 <1>

Functional Validations 
----------------------

Constraint: http://a.ml/vocabularies/amf/core#declaration-not-found
Severity: Violation
Message: not supported scalar for documentation
Target: null
Range: [(6,3)-(6,3)]
Location: file:///Users/myuser/Downloads/order-api-1.0.0-raml/order-api-1.0.0-raml

Conformance Validations <2>
-----------------------

Constraint: file:///exchange_modules/68ef9520-24e9-4cf2-b2f5-620025690913/anypoint-best-practices/1.0.0/ruleset.yaml#/encodes/validations/api-must-have-documentation <3>
Severity: Warning <4>
Message: Provide the documentation for the API. <5>
Target: amf://id#2 <6>
Range: [(2,0)-(6,4)] <7>
Location: file:///Users/myuser/Downloads/order-api-1.0.0-raml/order-api-1.0.0-raml <8>

Constraint: file:///exchange_modules/8a840abd-e63a-4f8b-87ab-24052eda2017/best-practices-ruleset/1.0.0/bestpractices.yaml#/encodes/validations/api-must-have-documentation
Severity: Violation
Message: Provide the documentation for the API
Target: amf://id#2
Range: [(2,0)-(6,4)]
Location: file:///Users/myuser/Downloads/order-api-1.0.0-raml/order-api-1.0.0-raml
----

<1> Total of functional and conformance validation issues found
<2> Conformance issues section 
<3> Ruleset and rule to which this set of issues applies 
<4> Severity level for the issue
<5> Description of the issue
<6> AMF model node ID; for information on the AMF model, see xref:api-governance::create-custom-rulesets.adoc#[Creating Custom Governance Rulesets] 
<7> Beginning line number and column and end line number and column in the API definition where the issue occurs, where column is the offset from the beginning of the line and numbering for the offset starts at 0
<8> The file in which the issue occurs, either the main file or one of its dependencies

// end::governance-api-validate[]

// tag::governance-document[]

[[governance-document]]
== governance document

`> governance document [options] <ruleset> <doc-file>`

This command creates the documentation for the API Governance ruleset definition ZIP file specified in `ruleset`. It puts the documentation in the `doc-file` ZIP file for you to upload and publish to Exchange. 

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

*Example command:*

[source,copy]
----
anypoint-cli governance document ~/temp/ruleset.yaml ~/temp/ruleset.doc.zip
----

*Example output:*

----
 validation name [ 'scalar-parameters' ]
 Saving to /Users/janedoe/temp/prof-1.doc.zip
----

// end::governance-document[]

// tag::governance-profile-create[]

[[governance-profile-create]]
== governance profile create

`> governance profile create [options] <profile-name> <ruleset-asset-identifiers>`

This command creates a governance profile using a string value for the new governance profile name specified in `profile-name`. 

You must include `ruleset-asset-identifiers`, a list with the group ID, asset ID, and version (gav), which is the unique asset identifiers for each ruleset. Use a comma separated list formatted as follows: `<group_id>/<asset_id>/<version>,<group_id>/<asset_id>/<version>` 

See <<exchange-asset-identifiers>>.

Besides the default options `--help`, `-f/--fields` and `-o/--output` options, this command also takes:

[cols="1,1"]
|===
|Option |Description

|--criteria <tags>
|The `criteria` option has the filters to apply to the profile to select the list APIs to which the profile rulesets will apply. The option is followed by a comma separated list of identifiers for tags, categories, and scope as follows: `tag:tag1,tag:tag2,category:catname:cat1,scope:apitype`

|--tags <tags> *Deprecated*
|*The `--criteria` option replaces the `tags` option starting with Anypoint CLI version v3.17.0.* The `tags` option is followed by a comma separated list of tags to be applied to the new governance profile, formatted as follows: `tag1,tag2,tag3`

|--description <description>
|The `description` option is followed by a string that is the new governance profile's description.
|===

*Example command:*

[source,copy]
----
anypoint-cli governance profile create "OAS Best Practices" 68ef9520-24e9-4cf2-b2f5-620025690913/open-api-best-practices/1.0.1 --criteria=tag:best --description "Profile for OAS Best Practices"
----

*Example output:*

----
 Profile Added
 Id         	4f98e59d-8efb-420f-ac95-9cd0af15bd45                                    
 Name       	OAS Best Practices                                                        
 Description	Profile for OAS Best Practices                                
 Rulesets   	gav://68ef9520-24e9-4cf2-b2f5-620025690913/open-api-best-practices/1.0.1
 Filter     	tag:best    
----

// end::governance-profile-create[]

// tag::governance-profile-delete[]

[[governance-profile-delete]]
== governance profile delete

`> governance profile delete [options] <profile-id>`

This command deletes a specific governance profile specified by `profile-id`. To get this ID, run the `governance profile info` or `governance profile list` command.

The `governance profile delete` command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

*Example command:*

[source,copy]
----
anypoint-cli governance profile delete 8ffd463f-86b2-4132-afc6-44d179209362
----

*Example output:*

----
 Profile with id 8ffd463f-86b2-4132-afc6-44d179209362 removed
----

// end::governance-profile-delete[]

// tag::governance-profile-info[]

[[governance-profile-info]]
== governance profile info

`> governance profile info [options] <profile-id>`

This command lists all information for a governance profile ID.

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

*Example command:*

[source,copy]
----
anypoint-cli governance profile info 8ffd463f-86b2-4132-afc6-44d179209362
----

*Example output:*

----
Id         	19fb211b-8775-43cc-865a-46228921d6ed                                                                                                    
Name       	Best Practices                                                                                                                          
Description	Best Practices Profile                                                                                                                  
Rulesets   	gav://3280b56c-e887-40f9-a9aa-db1118f719d5/best-practices/1.0.0 gav://68ef9520-24e9-4cf2-b2f5-620025690913/anypoint-best-practices/1.0.0
Filter     	tag:best 
----

// end::governance-profile-info[]

// tag::governance-profile-list[]

[[governance-profile-list]]
== governance profile list

`> governance profile list [options]`

This command lists information for all governance profiles for an organization. You need this information when updating a governance profile.

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

*Example command:*

[source,copy]
----
anypoint-cli governance profile list
----

*Example output:*

----
 Profile Name  	     Profile Id                          
	
 OAS Best Practices	 4f98e59d-8efb-420f-ac95-9cd0af15bd45

----
// end::governance-profile-list[]

// tag::governance-profile-update[]

[[governance-profile-update]]
== governance profile update

`> governance profile update [options] <profile-id>`

This command updates the governance profile specified in `profile-id`. To get this ID, run the `governance profile info` or `governance profile list` command.

You can update the governance profile's
governance name, rulesets, tags, and description. 

Besides the default options `--help`, `-f/--fields` and `-o/--output` options, this command also takes:

[cols="1,1"]
|===
|Option |Description

|--profile-name <profile-name>
|The `profile-name` option is followed by a string that is the new governance profile name.

|--ruleset-gavs <ruleset-gavs>
|The `ruleset-gavs` option is followed by comma-separated list with the group ID, asset ID, and version (GAV) for each ruleset, formatted as follows: `<group_id>/<asset_id>/<version>,<group_id>/<asset_id>/<version>` 

These are the asset's identifiers. See <<exchange-asset-identifiers>>.

|--tags <tags>
|The `tags` option is followed by a comma-separated list of tags formatted as follows: `tag1,tag2,tag3`.

|--description <description>
|The `description` option is followed by a string that is the new governance profile description.
|===

*Example command:*

[source,copy]
----
anypoint-cli governance profile update 51f9f94c-fb0c-43d4-9895-22c9e64f1537 --profile-name "New Name"
----

*Example output:*

----
 Profile updated 51f9f94c-fb0c-43d4-9895-22c9e64f1537
----

// end::governance-profile-update[]

// tag::governance-ruleset-clone[]

[[governance-ruleset-clone]]
== governance ruleset clone

`> governance ruleset clone [options] <ruleset> <new_title> <new_description>` 

This command clones a governance ruleset to create a new custom ruleset and applies specified updates to rules based on the options.

The `new-title` parameter gives the title for the new ruleset.

The `new description` parameter gives the description for the new ruleset.

TIP: Run the `governance ruleset info` command before running this command to get the rule ID information to use in this command.

Besides the default options `--help`, `-f/--fields` and `-o/--output` options, this command also takes:

[cols="1,1"]
|===
|Option |Description

|--remote
|Indicates that the ruleset to clone is published in Exchange and that the `ruleset` parameter is the asset identifier (GAV) for the ruleset.

|--error=<list_rules_to_move_to_error>
|The `error` option is followed by the rule IDs for the rules to move to the error severity level section of the ruleset YAML.

|--warning=<list_rules_to_move_to_warning> 
|The `warning` option is followed by the rule IDs for the rules to move to the warning severity level section of the ruleset YAML.

|--info=<list_rules_to_move_to_info> 
|The `info` option is followed by the rule IDs for the rules to move to the info severity level section of the ruleset YAML.

|--remove=<list_rules_to_disable> 
|The `remove` option is followed by the rule IDs for the rules to comment out, and therefore effectively disable, in the ruleset YAML. 
|===

*Example commands:*

[source,copy]
----
anypoint-cli governance ruleset clone ~/Downloads/ruleset.yaml 'New Ruleset from Clone' 'Cloned from ruleset.yaml' --warning=operation-default-response,operation-operationId >> mynewruleset.yaml

anypoint-cli governance ruleset clone 668ef6520-13e9-5cf2-c2f6-720225690914/anypoint-best-practices/1.0.2 'Custom Anypoint Best Practices' 'Cloned from MuleSoft Anypoint Best Practices' --remote --remove=openapi-tags,operation-tags >> my-anypoint-best-practices.yaml 

----

// end::governance-ruleset-clone[]

// tag::governance-ruleset-info[]

[[governance-ruleset-info]]
== governance ruleset info

`> governance ruleset info [options] <governance-ruleset>`

This command lists the ruleset rules in the ruleset definition passed in the `governance-ruleset` parameter. 

Besides the default options `--help`, `-f/--fields` and `-o/--output` options, this command also takes:

[cols="1,1"]
|===
|Option |Description

|--remote
|Indicates that the ruleset to clone is published in Exchange and that the `ruleset` parameter is the asset identifier (GAV) for the ruleset.
|===

*Example commands:*

[source,copy]
----
anypoint-cli governance ruleset info ~/temp/myruleset.yaml

anypoint-cli governance ruleset info 668ef6520-13e9-5cf2-c2f6-720225690914/anypoint-best-practices/1.0.2 --remote

----

*Example output:*

----
Ruleset /Users/myuser/temp/myruleset.yaml
Violation	operation-default-response
Violation	operation-operationId     
Warning  	operation-singular-tag    
Warning  	tag-description           
Warning  	info-contact              
Warning  	info-description          
Warning  	info-license              
Warning  	license-url               
Warning  	openapi-tags              
Warning  	operation-description     
Warning  	operation-tags            
Warning  	operation-tag-defined  
----

// end::governance-ruleset-info[]

// tag::governance-ruleset-init[]

[[governance-ruleset-init]]
== governance ruleset init

`> governance ruleset init [options] <schema>`

This command initializes a ruleset based on the data schema passed in the `schema` parameter. 

Besides the default options `--help`, `-f/--fields` and `-o/--output` options, this command also takes:

[cols="1,1"]
|===
|Option |Description

|--types <types>
|The `types` option gives the target types to export as rules.

|--name <name>
|The `name` option is the name of the ruleset.

|--output <output>
|The `output` option is the name of the ruleset YAML output file.
|===

*Example command:*

[source,copy]
----
anypoint-cli governance ruleset init --types=rest-api,async-api --name=my-ruleset --output=~/temp/myruleset.yaml mydataschema

----

*Example output:*

----
 xxx xxx
----

// end::governance-ruleset-init[]

// tag::governance-ruleset-validate[]

[[governance-ruleset-validate]]
== governance ruleset validate

`> governance ruleset validate [options] <governance-ruleset>`

This command validates the ruleset definitions passed using the `governance-ruleset` parameter. You can pass one of the following as the `governance-ruleset` parameter:

* A ruleset definition YAML file  
* A ZIP file that contains an API project with an `exchange.json` file that specifies the ruleset as the main file
* A folder that contains an API project with an `exchange.json` file that specifies the ruleset as the main file

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

*Example commands:*

[source,copy]
----
anypoint-cli governance ruleset validate ~/temp/myruleset.yaml

anypoint-cli governance ruleset validate ~/temp/myruleset.zip

anypoint-cli governance ruleset validate ~/temp/myrulesetfolder

----

*Example output for a valid ruleset:*

----
 Ruleset conforms with Dialect
----

*Example output for a nonvalid ruleset:*

----
Ruleset does not conform with Dialect
ModelId: file:///Users/janedoe/temp/prof-1-bad.yaml
Profile: Validation Profile 1.0
Conforms: false
Number of results: 1

Level: Violation

- Constraint: http://a.ml/amf/default_document#/declarations/profileNode_profile_required_validation
  Message: Property 'profile' is mandatory
  Severity: Violation
  Target: file:///Users/janedoe/temp/prof-1-bad.yaml#/encodes
  Property: http://schema.org/name
  Range: [(3,0)-(11,19)]
  Location: file:///Users/janedoe/temp/prof-1-bad.yaml
----

// end::governance-ruleset-validate[]

// tag::exchange-asset-identifier[]

[[exchange-asset-identifiers]]
=== Get Exchange Asset Identifiers (GAVs)

To get the GAVs for Exchange assets:

* If you are using the CLI, run the `anypoint-cli exchange asset list` command. 
* If you are using the web UI, select the asset in Exchange and then copy the group ID and asset ID from the URL. 

// end::exchange-asset-identifier[]