= CloudHub Applications

// tag::summary[]

[%header,cols="35a,65a"]
|===
|Command |Description
|<<runtime-mgr cloudhub-alert list>>| Lists all alerts in the environment
|<<runtime-mgr cloudhub-alert-history describe>>| Describes the history of the alarm
|<<runtime-mgr cloudhub-application list>>| Lists all applications in the environment
|<<runtime-mgr cloudhub-application describe>>| Show application details
|<<runtime-mgr cloudhub-application describe-json>>| Show raw application JSON response
|<<runtime-mgr cloudhub-application stop>>| Stop a running application
|<<runtime-mgr cloudhub-application start>>| Start an application
|<<runtime-mgr cloudhub-application restart>>| Restart a running application
|<<runtime-mgr cloudhub-application delete>>| Delete an application
|<<runtime-mgr cloudhub-application deploy>>| Deploy a new application
|<<runtime-mgr cloudhub-application modify>>| Modify an existing application, optionally updating the ZIP file
// |<<runtime-mgr application revert-runtime>>| Reverts application to its previous runtime
|<<runtime-mgr cloudhub-application download-logs>>| Download application logs to specified directory
|<<runtime-mgr cloudhub-application tail-logs>>| Tail application logs
|<<runtime-mgr cloudhub-application copy>>| Copies a CloudHub application
// |<<runtime-mgr cloudhub-application upgrade-runtime>>| Upgrades application runtime to the latest patch version or if a version if specified, to that version.
// |<<runtime-mgr cloudhub-application downgrade-runtime>>| Downgrades application runtime to the previous runtime version or if a version is specified, to that version.
|===

// end::summary[]


// tag::commands[]

== runtime-mgr cloudhub-alert list

----
> runtime-mgr cloudhub-alert list [options]
----
This command lists all alerts associated with your current environment.

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

== runtime-mgr cloudhub-alert-history describe

----
> runtime-mgr cloudhub-alert-history describe [options] <name>
----
This command describes the history of the alarm passed in `<name>`.

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

== runtime-mgr cloudhub-application list

----
> runtime-mgr cloudhub-application list [options]
----

This command lists all applications available in your Anypoint Platform CLI. It returns your application name, its status, the number of vCores assigned and the last time it was updated.

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

== runtime-mgr cloudhub-application describe

----
> runtime-mgr cloudhub-application describe [options] <name>
----

This command displays information on the application you pass in `<name>`. +
You can start typing your application's name and press `tab` for Anypoint Platform CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass. +
The command returns data such as the application's domain, its status, the last time it was updated, the Mule version, the ZIP file name, the region, monitoring, and workers; as well as `TRUE` or `FALSE` information for persistent queues and static IPs enablement.

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

== runtime-mgr cloudhub-application describe-json

----
> runtime-mgr cloudhub-application describe-json  [options] <name>
----

This command returns the raw JSON response of the application you specify in `<name>`.

You can start typing your application's name and press `tab` for Anypoint Platform CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass.

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

== runtime-mgr cloudhub-application stop

----
> runtime-mgr cloudhub-application stop  [options] <name>
----

This command stops the running application you specify in `<name>` +
You can start typing your application's name and press `tab` for Anypoint Platform CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass.

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

== runtime-mgr cloudhub-application start

----
> runtime-mgr cloudhub-application start [options] <name>
----

This command starts the running application you specify in `<name>` +
You can start typing your application's name and press `tab` for Anypoint Platform CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass.

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

== runtime-mgr cloudhub-application restart

----
> runtime-mgr cloudhub-application restart  [options] <name>
----

This command restarts the running application you specify in `<name>` +
You can start typing your application's name and press `tab` for Anypoint Platform CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass.

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

== runtime-mgr cloudhub-application delete

----
> runtime-mgr cloudhub-application delete [options] <name>
----

This command deletes the running application you specify in `<name>`.

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

[[deploy-to-cloudhub]]
== runtime-mgr cloudhub-application deploy

----
> runtime-mgr cloudhub-application deploy  [options] <name> <zipfile>
----

This command deploys the Mule deployable archive ZIP file that you specify in `<zipfile>` using the name you set in `<name>`. +
You can start typing your application's name and press `tab` for Anypoint Platform CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass. +
You will have to provide the absolute or relative path to the deployable ZIP file in your local hard drive and the name you give to your application has to be unique.

[NOTE]
If successful, this command's output includes the deployment status of `UNDEPLOYED`,
which indicates that CloudHub uploaded the application successfully.

The options this command can take are:
[%header,cols="30a,70a"]
|===
|Option |Description
|--runtime                                   | Name and version of the runtime environment. +
Use this option to specify the name and version of the runtime you want to deploy. +
Some examples of this value are `2.1.1-API-Gateway`, `3.9.1-visualizer` or   `4.1.1`. +
Tap your `tab` key after this option for the CLI to show you all your available options.
(This value is the latest CloudHub Runtime version by default.)
|--workers                                      | Number of workers. (This value is '1' by default)
|--workerSize                               | Size of the workers in vCores. (This value is '1' by default)
|--region                                        | Name of the region to deploy to. +
For a list of all supported regions, use the xref:cloudhub-dlb.adoc#cloudhub-region-list[cloudhub region list] command.
|--property                                    | Set a property (`name:value`). Can be specified multiple times. +
The property to be set must be passed enclosed in quotes and characters `:` and `=` must be escaped. +
(e.g. `--property "salesforce.password:qa\=34534"`).

Character `:` is not supported for the property's name.
|--propertiesFile                        | Overwrite all properties with values from this file. The file format is 1 or more lines in `name:value` format. Set the absolute path of the properties file in your local hard drive.
|--persistentQueues                   | Enable or disable persistent queues. Can take `true` or `false` values. (This value is `false` by default)
|--persistentQueuesEncrypted  | Enable or disable persistent queue encryption. Can take `true` or `false` values. (This value is `false` by default)
|--staticIPsEnabled                                      | Enable or disable static IPs. Can take `true` or `false` values. (This value is `false` by default)
|--objectStoreV1                   | Enable or disable Object Store V1. Can take `true` or `false` values
|--autoRestart                            | Automatically restart app when not responding. Can take `true` or `false` values. (This value is `true` by default.)
|--help                                                  | output usage information
|===
Note that from Anypoint Platform CLI you won't be able to allocate static IPs. You can simply enable and disable them.

After typing any option, you can double tap the `tab` key for a full list of all possible options.
For example:
----
> deploy <app name> --runtime [tab][tab]
----
Lists all possible runtimes you can select.

[IMPORTANT]
====
If you deploy without using any options, your application will deploy using all your default values.
====

== runtime-mgr cloudhub-application modify

----
> runtime-mgr cloudhub-application modify  [options] <name> [zipfile]
----
This command updates the settings of an existing application. Optionally you can update it by uploading a new ZIP file. +
You can start typing your application's name and press `tab` for Anypoint Platform CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass.
This command can take all the same options as the `deploy` option.

[NOTE]
This command's output includes `Status`, which is the application's previous deployment status state.

You can also start typing your option and press `tab` for Anypoint Platform CLI to autocomplete it for you.

//TODO Check revert-runtime deprecation
// == runtime-mgr application revert-runtime
//
// [source,Example]
// ----
// > runtime-mgr application revert-runtime [options] <name>
// ----
// This command reverts the application defined in `<name>` to its previous runtime environment. +
// You can start typing your application's name and press `tab` for Anypoint Platform CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass.

// CLI DEFAULTS
// include::partial$cli-default-options.adoc[tag=CLIdefaultOptions]

== runtime-mgr cloudhub-application download-logs

----
> runtime-mgr cloudhub-application download-logs [options] <name> <directory>
----
This command downloads logs the for application specified in `<name>` to the specified directory.

You can start typing your application's name and press `tab` for Anypoint Platform CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass.

Keep in mind that contrarily to what you see in the UI, the logs you download from the CLI won't separate system logs from worker logs.

== runtime-mgr cloudhub-application tail-logs

----
> runtime-mgr cloudhub-application tail-logs [options] <name>
----

This command tails application logs. +
You can start typing your application's name and press `tab` for Anypoint Platform CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass.

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

// == runtime-mgr cloudhub-application upgrade-runtime
//
// [source,Example]
// ----
// > runtime-mgr cloudhub-application upgrade-runtime [options] <name>
// ----
//
// This command upgrades the runtime version of the application passed in `name` to the latest patch version. If the `-v`/`--version` option is used to specify a specific runtime version, this command updates the application's runtime to that version. +
// Besides the `--version` option, this command also takes the default `--help`, `-f`/`--fields` and `-o`/`--output` options.
//
// == runtime-mgr cloudhub-application downgrade-runtime
//
// [source,Example]
// ----
// > runtime-mgr cloudhub-application downgrade-runtime [options] <name>
// ----
// This command downgrades the runtime version of the application passed in `name` to the previous runtime version. If the `-v`/`--version` option is used to specify a specific runtime version, this command updates the application's runtime to that version. +
// Besides the `--version` option, this command also takes the default `--help`, `-f`/`--fields` and `-o`/`--output` options.

== runtime-mgr cloudhub-application copy

----
> runtime-mgr cloudhub-application copy [options] <source> <target>
----

This command copies the CloudHub application passed in `source` to the target passed in `target`.

Arguments `source` and `target` should be formatted as follows: `([group_id]/)<asset_id>/<version>`.

If `group_id` is not specified, it defaults to the currently selected Organization ID.

For example:

----
> runtime-mgr cloudhub-application copy Services:QA/application-1 Development:QA/application-2
----
Copies the application named `application-1` from the QA environment of the Services organization to the QA environment of the Development organization. +
If the Anypoint Platform CLI is using the QA environment in the Services organization, the command can simply take the application name as a `source`:

----
> runtime-mgr cloudhub-application copy application-1 Development/QA/application-2
----

[NOTE]
Running this command requires your user to have read/write access to the `/tmp` directory of the OS where CLI is installed.

In addition to the default `--help`, `-f`/`--fields` and `-o`/`--output` options, this command also takes:

[%header,cols="30a,70a"]
|===
|Option |Description
|--property  | Set a property (`name:value`). Can be specified multiple times.

Enclose the property in quotes and escape the `:` and `=` characters,
for example:

`--property "salesforce.password:qa\=34534"`
|===

[NOTE]
When copying an application containing safely hidden application properties, pass the properties in the `copy` command using the `--property` option.
For information about safely hidden application properties, see xref:runtime-manager::secure-application-properties.adoc[Safely Hide Application Properties].

// end::commands[]
