= CLI for Cloudhub 2.0

Use these commands for applications in Cloudhub 2.0.

// tag::summary[]

[%header,cols="35a,65a"]
|===
|Command |Description
|xref:anypoint-cli::cloudhub2-apps.adoc#runtime-mgr-application-delete[runtime-mgr:application:delete] | Deletes an application
|xref:anypoint-cli::cloudhub2-apps.adoc#runtime-mgr-application-describe[runtime-mgr:application:describe] | Describes an application
// | <<runtime-mgr-application-describe-json>> | Describes an application in a raw JSON response
|xref:anypoint-cli::cloudhub2-apps.adoc#runtime-mgr-application-download-logs[runtime-mgr:application:download:logs] | Downloads logs of an application from a specification to a specified directory
|xref:anypoint-cli::cloudhub2-apps.adoc#runtime-mgr-application-list[runtime-mgr:application:list] | Lists all applications in an organization
|xref:anypoint-cli::cloudhub2-apps.adoc#runtime-mgr-application-modify[runtime-mgr:application:modify] | Modifies a deployed application
|xref:anypoint-cli::cloudhub2-apps.adoc#runtime-mgr-application-start[runtime-mgr:application:start] | Starts a stopped application
|xref:anypoint-cli::cloudhub2-apps.adoc#runtime-mgr-application-stop[runtime-mgr:application:stop] | Stops running an application
|xref:anypoint-cli::cloudhub2-apps.adoc#runtime-mgr-application-logs[runtime-mgr:application:logs] | Tails an application's logs from a specification
|===

NOTE: These commands can be used for Cloudhub 2.0 and Runtime Fabric applications.

// end::summary[]


// tag::commands[]
[[runtime-mgr-application-delete]]
== runtime-mgr:application:delete

----
> runtime-mgr:application:delete [flags] <appID>
----
Deletes the running application specified in `<appID>`. To get this ID, run the `runtime-mgr application list` command.

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

This command accepts only the default flag `--help`.




[[runtime-mgr-application-describe]]
== runtime-mgr:application:describe

----
> runtime-mgr:application:describe [flags] <appID>
----
Displays information about the application specified in `<appID>`. To get this ID, run the `runtime-mgr application list` command.

This command has the `--output` flag. Use the `--output` flag to specify the response format. Supported values are `table` (default) and `json`.

This command also accepts the default flag `--help`.

[[runtime-mgr-application-download-logs]]
== runtime-mgr:application:download-logs

----
> runtime-mgr:application:download-logs [flags] <appID> <directory> <specID>
----

Downloads logs for the application specified in `<appID>` from the specification specified in `<specID>` to the selected directory.

To get the `<appID>`, run the `runtime-mgr application list` command.

To get the `<specID>` run the `runtime-mgr application describe` command.

This command accepts only the default flag `--help`.

[[runtime-mgr-application-list]]
== runtime-mgr:application:list

----
> runtime-mgr:application:list [flags]
----
Lists all applications in your organization.

This command has the `--output` flag. Use the `--output` flag to specify the response format. Supported values are `table` (default) and `json`.

This command accepts the default flag `--help`.


[[runtime-mgr-application-modify]]
== runtime-mgr:application:modify

----
> runtime-mgr:application:modify <appID> <certificateName> [flags]
----
Updates the settings of an existing application specified in `<appID>`.
To get the `<appID>`, run the `runtime-mgr application list` command.

Besides the default `--help` flag, this command also takes:

[%header,cols="12a,53a,35a"]
|===
|Flag |Description |Example
|`--artifactId` |ID of the application retrieved from Exchange. | `--artifactId mule-maven-plugin`
|`--assetVersion` | Version of the Exchange application to use. +
Default: latest application version | `-assetVersion 2.0.4`
|`--[no-]clustered`| Enables clustered nodes, which requires at least two replicas. +
Default: `disabled` |`--no-clustered`
|`--[no-]disableAmLogForwarding`| Disables forwarding applications logs to Anypoint Monitoring. +
Default: `enabled` |`--disableAmLogForwarding`
|`--[no-]forwardSslSession`| Enables SSL session forwarding. +
Default: `disabled` | `--no-forwardSslSession`
|`--groupId` | Group ID of the asset to deploy. +
Default: selected organization ID.| `--groupId org.mule.testgroup`
|`--[no-]lastMileSecurity`| Enables Last Mile Security. +
Default: `disabled` | `--no-lastMileSecurity`
|`--[no-]objectStoreV2`| Enables object store v2. +
Default: `disabled`  | `--no-objectStoreV2`
|`--pathRewrite`| Supplies the base path expected by the HTTP listener in your application. +
Format: must begin with `/` | `--pathRewrite /http://localhost:3000`.
|`--property`| Sets a property. +
Format: `name:value` | `--property testproperty:true`
|`--propertiesFile`| Replaces all properties with values from a selected file. +
Format: one or more lines in `name: value` style | `--propertiesFile /Users/mule/Documents/properties.txt`
|`--publicEndpoints`| Supplies endpoints to reach via the public internet. +
 Format: separated by commas, no spaces | `--publicEndpoints my-superapp-example: /status?limit=10`
|`--replicas` | Number of replicas. Must be above `0`. +
Default: `1` | `--replicas 2`
|`--replicaSize`| Size of replicas in Vcores. +
Default: `0.1` | `--replicaSize 0.5`
|`--runtimeVersion` |Runtime version of the deployment target.|`--runtimeVersion 4.4.0`
|`--secureProperty` | Sets an encripted property. | `--secureProperty secureTestProperty:true`
|`--scopeLoggingConfig`| Defines scope logging. +
Format: `scopeName: logLevel`, separated by commas, no spaces | 
`--scopeLoggingConfig testscope1:WARN,testscope2:DEBUG`
|`--scopeLoggingConfigFile`| Uploads a file to define scope logging. +
Format: 1 tuple per line, style: `{scope: scopeName, logLevel: logLevelType}` enclosed with `{}` `()` or `[]` |`--scopeLoggingConfigFile /Users/mule/Documents/cert.txt`
|`--updateStrategy`| Updates the strategy used. +
Default: `rolling` | `--updateStrategy recreate`

|===

NOTE: This command has multi-option flags. When using multi-option flags in a command, either put the parameter before the flags or use a `-- ` (two dashes followed by a space) before the parameter.

[[runtime-mgr-application-start]]
== runtime-mgr:application:start

----
> runtime-mgr:application:start [flags] <appid>
----
Starts running the application specified in `<appid>`. To get this ID, run the `runtime-mgr application list` command.

This command accepts only the default flag `--help`.

[[runtime-mgr-application-stop]]
== runtime-mgr:application:stop

----
> runtime-mgr:application:stop [flags] <appID>
----
Stops running the application specified in `<appID>`. To get this ID, run the `runtime-mgr application list` command.

This command accepts only the default flag `--help`.

[[runtime-mgr-application-logs]]
== runtime-mgr:application:logs

----
> runtime-mgr:application:logs [flags] <appID> <specID>
----
Tails application logs for the application specificied in `<appID>` from the specification specified in `<specID>`.

To get the `<appID>`, run the `runtime-mgr application list` command.

To get the `<specID>`, run the `runtime-mgr application describe` command.


This command accepts only the default flag `--help`.

== runtime-mgr:application:delete

----
> runtime-mgr:application:delete [flags] <appID>
----
Deletes the running application specified in `<appID>`. To get this ID, run the `runtime-mgr application list` command.

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

This command accepts only the default flag `--help`.

== runtime-mgr:application:describe

----
> runtime-mgr:application:describe [flags] <appID>
----
Displays information about the application specified in `<appID>`. To get this ID, run the `runtime-mgr application list` command.

This command accepts only the default flag `--help`.

// [[runtime-mgr-application-describe-json]]
// == runtime-mgr:application:describe-json

//----
//> runtime-mgr:application:describe-json [options] <appID>
//----
//Displays a raw JSON response from the application specified in `<appID>`. To get this ID, run the `runtime-mgr application list` command.

//This command accepts only the default option `--help`.

== runtime-mgr:application:download-logs

----
> runtime-mgr:application:download-logs [flags] <appID> <directory> <specID>
----

Downloads logs for the application specified in `<appID>` from the specification specified in `<specID>` to the selected directory.

To get the `<appID>`, run the `runtime-mgr application list` command.

To get the `<specID>` run the `runtime-mgr application describe` command.

This command accepts only the default flag `--help`.

== runtime-mgr:application:list

----
> runtime-mgr:application:list [flags]
----
Lists all applications in your organization.

This command accepts only the default flag `--help`.

== runtime-mgr:application:modify

----
> runtime-mgr application modify [flags] <appID> <certificateName>
----
Updates the settings of an existing application specified in `<appID>`.
To get the `<appID>`, run the `runtime-mgr application list` command.

Besides the default `--help` flag, this command also takes:

[%header,cols="12a,53a,35a"]
|===
|Flag |Description |Example
|`--artifactId` |ID of the application retrieved from Exchange. | `--artifactId mule-maven-plugin`
|`--assetVersion` | Version of the Exchange application to use. +
Default: latest application version | `-assetVersion 2.0.4`
|`--[no-]clustered`| Enables clustered nodes, which requires at least two replicas. +
Default: `disabled` |`--no-clustered`
|`--[no-]disableAmLogForwarding`| Disables forwarding applications logs to Anypoint Monitoring. +
Default: `enabled` |`--disableAmLogForwarding`
|`--[no-]forwardSslSession`| Enables SSL session forwarding. +
Default: `disabled` | `--no-forwardSslSession`
|`--groupId` | Group ID of the asset to deploy. +
Default: selected organization ID.| `-groupId org.mule.testgroup`
|`--[no-]lastMileSecurity`| Enables Last Mile Security. +
Default: `disabled` | `--no-lastMileSecurity`
|`--[no-]objectStoreV2`| Enables object store v2. +
Default: `disabled` | `--no-objectStoreV2`
|`--pathRewrite`| Supplies the base path expected by the HTTP listener in your application. +
Format: must begin with `/` | `--pathRewrite /http://localhost:3000`.
|`--property`| Sets a property. +
Format: `name:value` | `--property testproperty:true`
|`--propertiesFile`| Replaces all properties with values from a selected file. +
Format: one or more lines in `name: value` style | `--propertiesFile /Users/mule/Documents/properties.txt`
|`--publicEndpoints`| Supplies endpoints to reach via the public internet. +
 Format: separated by commas, no spaces | `--publicEndpoints my-superapp-example: /status?limit=10`
|`--replicas` | Number of replicas. Must be above `0`. +
Default: `1` | `--replicas 2`
|`--replicaSize`| Size of replicas in Vcores. +
Default: `0.1` | `--replicaSize 0.5`
|`--runtimeVersion` |Runtime version of the deployment target.|`--runtimeVersion 1.0.1`
|`--scopeLoggingConfig`| Defines scope logging. +
Format: `scopeName: logLevel`, separated by commas, no spaces | `--scopeLoggingConfig testscope1:WARN,testscope2:DEBUG`
|`--scopeLoggingConfigFile`| Uploads a file to define scope logging. +
Format: 1 tuple per line, style: `{scope: scopeName, logLevel: logLevelType}` enclosed with `{}` `()` or `[]` |`--scopeLoggingConfigFile /Users/mule/Documents/cert.txt`
|`--updateStrategy`| Updates the strategy used. +
Default: `rolling` | `--updateStrategy recreate`

|===
== runtime-mgr:application:start

----
> runtime-mgr:application:start [flags] <appID>
----
Starts running the application specified in `<appID>`. To get this ID, run the `runtime-mgr application list` command.

This command accepts only the default flag `--help`.

== runtime-mgr:application:stop

----
> runtime-mgr:application:stop [flags] <appID>
----
Stops running the application specified in `<appID>`. To get this ID, run the `runtime-mgr application list` command.

This command accepts only the default flag `--help`.

== runtime-mgr:application:logs

----
> runtime-mgr:application:logs [flags] <appID> <specID>
----
Tails application logs for the application specificied in `<appID>` from the specification specified in `<specID>`.

To get the `<appID>`, run the `runtime-mgr application list` command.

To get the `<specID>`, run the `runtime-mgr application describe` command.


This command accepts only the default flag `--help`.



// end::commands[]
