= CLI for Cloudhub 2.0

Use these commands for applications in Cloudhub 2.0.

// tag::summary[]

[%header,cols="35a,65a"]
|===
|Command |Description
|<<runtime-mgr-application-delete>> | Deletes an application
|<<runtime-mgr-application-deploy>> | Deploys an application to a specified target using an Exchange application and runs the specified runtime version
|<<runtime-mgr-application-describe>> | Describes an application
// | <<runtime-mgr-application-describe-json>> | Describes an application in a raw JSON response
|<<runtime-mgr-application-download-logs>> | Downloads logs of an application from a specification to a specified directory 
|<<runtime-mgr-application-list>> | Lists all applications in an organization
|<<cloudhub2-apps.adoc>> | Modifies a deployed application
|<<runtime-mgr-application-start>> | Starts a stopped application
|<<runtime-mgr-application-stop>> | Stops running an application
|<<runtime-mgr-application-logs>> | Tails an application's logs from a specification 
|===

// end::summary[]

// tag::summary-rtf[]

[%header,cols="35a,65a"]
|===
|Command |Description
|<<runtime-mgr-application-delete>> | Deletes an application
|<<runtime-mgr-application-describe>> | Describes an application
|<<runtime-mgr-application-download-logs>> | Downloads logs of an application from a specification to a specified directory 
|<<runtime-mgr-application-list>> | Lists all applications in an organization
|<<runtime-mgr-application-modify>> | Modifies a deployed application
|<<runtime-mgr-application-start>> | Starts a stopped application
|<<runtime-mgr-application-stop>> | Stops running an application
|<<runtime-mgr-application-logs>> | Tails an application's logs from a specification 
|===

// end::summary-rtf[]

// tag::commands[]
[[runtime-mgr-application-delete]]
== runtime-mgr:application:delete

----
> runtime-mgr:application:delete [options] <appID>
----
Deletes the running application specified in `<appID>`. To get this ID, run the `runtime-mgr application list` command.

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

This command accepts only the default option `--help`.

[[runtime-mgr-application-deploy]]
== runtime-mgr:application:deploy

----
> runtime-mgr:application:deploy [options] <appID> <deploymentTargetID> <runtimeVersion> <artifactID> 
----
Deploys the application specified in `<appID>` to the deployment target specified using the following options:

[%header,cols="12a,53a,35a"]
|===
|Value |Description | Example
|`ArtifactId` |Artifact ID of the application retrieved from Exchange. | `mule-test-plugin`
|`deploymentTargetID` |ID of the deployment target. +
You can get this ID directly from Runtime Manager.  | `cloudhub-app-northeast-1`
|`name` |Name of the application to deploy. | `testCloudhub2app`
|`runtimeVersion` |Runtime version of the deployment target.|`4.4.0`

|===

Besides the default `--help` option this command also takes:

[%header,cols="12a,53a,35a"]
|===
|Value |Description |Example
|`assetVersion` | Version of the Exchange application to use. +
Default: latest application version | `2.0.4`
|`clustered`| Enables clustered nodes, which requires at least two replicas. +
 Default:.`disabled` +
Supported values: `true`, `false` |`false` 
|`disableAmLogForwarding`| Disables forwarding applications logs to Anypoint Monitoring. +
Default: `enabled` +
Supported values: `true`, `false` |`true`
|`forwardSslSession`| Enables SSL session forwarding. +
Default: `disabled` +
Values: `true`, `false`| `false`
|`groupID` | Group ID of the asset to deploy. +
Default: selected organization ID | `org.mule.test`
|`lastMileSecurity`| Enables Last Mile Security. +
Default: `disabled` +
Supported values: `true`, `false` | `true`
|`objectStoreV2`| Enables Object Store v2. +
Default: `disabled` +
 Supported values: `true`, `false` | `true`
|`pathRewrite`| Supplies the base path expected by the HTTP listener in your application. +
Format: must begin with `/` | `/http://localhost:3000`
|`property`| Sets a property. +
Format: `name:value` | `testproperty:true`
|`propertiesFile`| Replaces all properties with values from a selected file. +
Format: one or more lines in `name: value` style | `/Users/mule/Documents/properties.txt`
|`publicEndpoints`| Supplies endpoints to reach via the public internet. +
Format: separated by commas, no spaces | `my-superapp-example:/status?limit=10`
|`replicas` | Number of replicas. Must be above `0`. +
Default: `1` | `2`
|`replicaSize`| Size of replicas in Vcores. +
Default: `0.1` | `0.5`
|`scopeLoggingConfig`| Defines scope logging. +
Format: `scopeName: logLevel`, separated by commas, no spaces | ``testscope1:WARN,testscope2:DEBUG``
|`scopeLoggingConfigFile`| Uploads a file to define scope logging. +
Format: one tuple per line, style: `{scope: scopeName, logLevel: logLevelType}` enclosed with `{}` `()` or `[]` |`/Users/mule/Documents/cert.txt`
|`updateStrategy`| Updates the strategy used. +
Default: `rolling` | `recreate`
|===

[[runtime-mgr-application-describe]]
== runtime-mgr:application:describe 

----
> runtime-mgr:application:describe [options] <appID>
----
Displays information about the application specified in `<appID>`. To get this ID, run the `runtime-mgr application list` command.

This command accepts only the default option `--help`.

[[runtime-mgr-application-download-logs]]
== runtime-mgr:application:download-logs

----
> runtime-mgr:application:download-logs [options] <appID> <directory> <specID> 
----

Downloads logs for the application specified in `<appID>` from the specification specified in `<specID>` to the selected directory.

To get the `<appID>`, run the `runtime-mgr application list` command.

To get the `<specID>` run the `runtime-mgr application describe` command.

This command accepts only the default option `--help`.

[[runtime-mgr-application-list]]
== runtime-mgr:application:list

----
> runtime-mgr:application:list [options]
----
Lists all applications in your organization. 

This command accepts only the default option `--help`.

[[runtime-mgr-application-modify]]
== runtime-mgr:application:modify

----
> runtime-mgr:application:modify [options] <appID> <certificateName>
----
Updates the settings of an existing application specified in `<appID>`. 
To get the `<appID>`, run the `runtime-mgr application list` command.

Besides the default `--help` option, this command also takes:

[%header,cols="12a,53a,35a"]
|===
|Value |Description |Example
|`ArtifactId` |ID of the application retrieved from Exchange. | `mule-maven-plugin`
|`assetVersion` | Version of the Exchange application to use. +
Default: latest application version | `2.0.4`
|`clustered`| Enables clustered nodes, which requires at least two replicas. +
Default: `disabled` +
Supported values: `true`, `false` |`false` 
|`disableAmLogForwarding`| Disables forwarding applications logs to Anypoint Monitoring. +
Default: `enabled` +
Supported values: `true`, `false` |`true`
|`forwardSslSession`| Enables SSL session forwarding. +
Default: `disabled` +
Values: `true`, `false`| `false`
|`groupID` | Group ID of the asset to deploy. +
Default: selected organization ID.| `org.mule.testgroup`
|`lastMileSecurity`| Enables Last Mile Security. +
Default: `disabled` +
Supported values: `true`, `false` | `true`
|`objectStoreV2`| Enables object store v2. +
Default: `disabled` +
Supported values: `true`, `false` | `true`
|`pathRewrite`| Supplies the base path expected by the HTTP listener in your application. +
Format: must begin with `/` | `/http://localhost:3000`.
|`property`| Sets a property. +
Format: `name:value` | `testproperty:true`
|`propertiesFile`| Replaces all properties with values from a selected file. +
Format: one or more lines in `name: value` style | `/Users/mule/Documents/properties.txt`
|`publicEndpoints`| Supplies endpoints to reach via the public internet. +
 Format: separated by commas, no spaces | `my-superapp-example: /status?limit=10`
|`replicas` | Number of replicas. Must be above `0`. +
Default: `1` | `2`
|`replicaSize`| Size of replicas in Vcores. +
Default: `0.1` | `0.5`
|`runtimeVersion` |Runtime version of the deployment target.|`4.4.0`
|`scopeLoggingConfig`| Defines scope logging. +
Format: `scopeName: logLevel`, separated by commas, no spaces | `testscope1:WARN,testscope2:DEBUG`
|`scopeLoggingConfigFile`| Uploads a file to define scope logging. +
Format: 1 tuple per line, style: `{scope: scopeName, logLevel: logLevelType}` enclosed with `{}` `()` or `[]` |`/Users/mule/Documents/cert.txt`
|`updateStrategy`| Updates the strategy used. +
Default: `rolling` | `recreate`

|===
[[runtime-mgr-application-start]]
== runtime-mgr:application:start

----
> runtime-mgr:application:start [options] <appid>
----
Starts running the application specified in `<appid>`. To get this ID, run the `runtime-mgr application list` command.

This command accepts only the default option `--help`.

[[runtime-mgr-application-stop]]
== runtime-mgr:application:stop

----
> runtime-mgr:application:stop [options] <appID>
----
Stops running the application specified in `<appID>`. To get this ID, run the `runtime-mgr application list` command.

This command accepts only the default option `--help`.

[[runtime-mgr-application-logs]]
== runtime-mgr:application:logs

----
> runtime-mgr:application:logs [options] <appID> <specID> 
----
Tails application logs for the application specificied in `<appID>` from the specification specified in `<specID>`.

To get the `<appID>`, run the `runtime-mgr application list` command.

To get the `<specID>`, run the `runtime-mgr application describe` command.


This command accepts only the default option `--help`.



// end::commands[]

// tag::commands-rtf[]

[[runtime-mgr-application-delete]]
== runtime-mgr:application:delete

----
> runtime-mgr:application:delete [options] <appID>
----
Deletes the running application specified in `<appID>`. To get this ID, run the `runtime-mgr application list` command.

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

This command accepts only the default option `--help`.

[[runtime-mgr-application-describe]]
== runtime-mgr:application:describe 

----
> runtime-mgr:application:describe [options] <appID>
----
Displays information about the application specified in `<appID>`. To get this ID, run the `runtime-mgr application list` command.

This command accepts only the default option `--help`.

// [[runtime-mgr-application-describe-json]]
// == runtime-mgr:application:describe-json 

//----
//> runtime-mgr:application:describe-json [options] <appID>
//----
//Displays a raw JSON response from the application specified in `<appID>`. To get this ID, run the `runtime-mgr application list` command.

//This command accepts only the default option `--help`. 

[[runtime-mgr-application-download-logs]]
== runtime-mgr:application:download-logs

----
> runtime-mgr:application:download-logs [options] <appID> <directory> <specID> 
----

Downloads logs for the application specified in `<appID>` from the specification specified in `<specID>` to the selected directory.

To get the `<appID>`, run the `runtime-mgr application list` command.

To get the `<specID>` run the `runtime-mgr application describe` command.

This command accepts only the default option `--help`.

[[runtime-mgr-application-list]]
== runtime-mgr:application:list

----
> runtime-mgr:application:list [options]
----
Lists all applications in your organization. 

This command accepts only the default option `--help`.

[[runtime-mgr-application-modify]]
== runtime-mgr:application:modify

----
> runtime-mgr application modify [options] <appID> <certificateName>
----
Updates the settings of an existing application specified in `<appID>`. 
To get the `<appID>`, run the `runtime-mgr application list` command.

Besides the default `--help` option, this command also takes:

[%header,cols="12a,53a,35a"]
|===
|Value |Description |Example
|`ArtifactId` |ID of the application retrieved from Exchange. | `mule-maven-plugin`
|`assetVersion` | Version of the Exchange application to use. +
Default: latest application version | `2.0.4`
|`clustered`| Enables clustered nodes, which requires at least two replicas. +
Default: `disabled` +
Supported values: `true`, `false` |`false` 
|`disableAmLogForwarding`| Disables forwarding applications logs to Anypoint Monitoring. +
Default: `enabled` +
Supported values: `true`, `false` |`true`
|`forwardSslSession`| Enables SSL session forwarding. +
Default: `disabled` +
Values: `true`, `false`| `false`
|`groupID` | Group ID of the asset to deploy. +
Default: selected organization ID.| `org.mule.testgroup`
|`lastMileSecurity`| Enables Last Mile Security. +
Default: `disabled` +
Supported values: `true`, `false` | `true`
|`objectStoreV2`| Enables object store v2. +
Default: `disabled` +
Supported values: `true`, `false` | `true`
|`pathRewrite`| Supplies the base path expected by the HTTP listener in your application. +
Format: must begin with `/` | `/http://localhost:3000`.
|`property`| Sets a property. +
Format: `name:value` | `testproperty:true`
|`propertiesFile`| Replaces all properties with values from a selected file. +
Format: one or more lines in `name: value` style | `/Users/mule/Documents/properties.txt`
|`publicEndpoints`| Supplies endpoints to reach via the public internet. +
 Format: separated by commas, no spaces | `my-superapp-example: /status?limit=10`
|`replicas` | Number of replicas. Must be above `0`. +
Default: `1` | `2`
|`replicaSize`| Size of replicas in Vcores. +
Default: `0.1` | `0.5`
|`runtimeVersion` |Runtime version of the deployment target.|`1.0.1`
|`scopeLoggingConfig`| Defines scope logging. +
Format: `scopeName: logLevel`, separated by commas, no spaces | `testscope1:WARN,testscope2:DEBUG`
|`scopeLoggingConfigFile`| Uploads a file to define scope logging. +
Format: 1 tuple per line, style: `{scope: scopeName, logLevel: logLevelType}` enclosed with `{}` `()` or `[]` |`/Users/mule/Documents/cert.txt`
|`updateStrategy`| Updates the strategy used. +
Default: `rolling` | `recreate`

|===
[[runtime-mgr-application-start]]
== runtime-mgr:application:start

----
> runtime-mgr:application:start [options] <appID>
----
Starts running the application specified in `<appID>`. To get this ID, run the `runtime-mgr application list` command.

This command accepts only the default option `--help`.

[[runtime-mgr-application-stop]]
== runtime-mgr:application:stop

----
> runtime-mgr:application:stop [options] <appID>
----
Stops running the application specified in `<appID>`. To get this ID, run the `runtime-mgr application list` command.

This command accepts only the default option `--help`.

[[runtime-mgr-application-logs]]
== runtime-mgr:application:logs

----
> runtime-mgr:application:logs [options] <appID> <specID> 
----
Tails application logs for the application specificied in `<appID>` from the specification specified in `<specID>`.

To get the `<appID>`, run the `runtime-mgr application list` command.

To get the `<specID>`, run the `runtime-mgr application describe` command.


This command accepts only the default option `--help`.



// end::commands-rtf[]