= CloudHub Applications

// tag::summary[]

[%header,cols="35a,65a"]
|===
|Command |Description
|xref:anypoint-cli::cloudhub-apps.adoc#runtime-mgr-cloudhub-alert-list[runtime-mgr:cloudhub:alert:list] | Lists all alerts in the environment
|xref:anypoint-cli::cloudhub-apps.adoc#runtime-mgr-cloudhub-alert-history-describe[runtime-mgr:cloudhub:alert:history:describe] | Describes the history of the alarm
|xref:anypoint-cli::cloudhub-apps.adoc#runtime-mgr-cloudhub-application-list[runtime-mgr:cloudhub:application:list]| Lists all applications in the environment
|xref:anypoint-cli::cloudhub-apps.adoc#runtime-mgr-cloudhub-application-describe[runtime-mgr:cloudhub:application:describe] | Shows application details
// |<<runtime-mgr-cloudhub-application-describe-json>> | Show raw application JSON response
|xref:anypoint-cli::cloudhub-apps.adoc#runtime-mgr-cloudhub-application-stop[runtime-mgr:cloudhub:application:stop] | Stops a running application
|xref:anypoint-cli::cloudhub-apps.adoc#runtime-mgr-cloudhub-application-start[runtime-mgr:cloudhub:application:start] | Starts an application
|xref:anypoint-cli::cloudhub-apps.adoc#runtime-mgr-cloudhub-application-restart[runtime-mgr:cloudhub:application:restart] | Restarts a running application
|xref:anypoint-cli::cloudhub-apps.adoc#runtime-mgr-cloudhub-application-delete[runtime-mgr:cloudhub:application:delete]| Deletes an application
|xref:anypoint-cli::cloudhub-apps.adoc#deploy-to-cloudhub[runtime-mgr:cloudhub:application:deploy] | Deploys a new application
|xref:anypoint-cli::cloudhub-apps.adoc#runtime-mgr-cloudhub-application-modify[runtime-mgr:cloudhub:application:modify]| Modifies an existing application, optionally updating the ZIP file
// |<<runtime-mgr application revert-runtime]| Reverts application to its previous runtime
|xref:anypoint-cli::cloudhub-apps.adoc#runtime-mgr-cloudhub-application-download-logs[runtime-mgr:cloudhub:application:download:logs] | Download application logs to specified directory
|xref:anypoint-cli::cloudhub-apps.adoc#runtime-mgr-cloudhub-application-tail-logs[runtime-mgr:cloudhub:application:tail:logs] | Tail application logs
|xref:anypoint-cli::cloudhub-apps.adoc#runtime-mgr-cloudhub-application-copy[runtime-mgr:cloudhub:application:copy] | Copies a CloudHub application
// |<<runtime-mgr-cloudhub-application-upgrade-runtime[>> | Upgrades application runtime to the latest patch version or if a version if specified, to that version.
// |<<runtime-mgr-cloudhub-application-downgrade-runtime>> | Downgrades application runtime to the previous runtime version or if a version is specified, to that version.
|xref:anypoint-cli::cloudhub-apps.adoc#cloudhub-region-list[cloudhub:region:list] | Lists all supported regions
|xref:anypoint-cli::cloudhub-aps.adoc#cloudhub-runtime-list[cloudhub:runtime:list] | Lists all available runtimes
|===

// end::summary[]


// tag::commands[]

[[runtime-mgr-cloudhub-alert-list]]
== runtime-mgr:cloudhub-alert:list

----
> runtime-mgr:cloudhub-alert:list [flags]
----
This command lists all alerts associated with your current environment.

This command has the `--output` flag. Use the `--output` flag to specify the response format. Supported values are `table` (default) and `json`

This command also accepts the default flag `--help`.

[[runtime-mgr-cloudhub-alert-history-describe]]
== runtime-mgr:cloudhub-alert-history:describe

----
> runtime-mgr:cloudhub-alert-history:describe [flags] <name>
----
This command describes the history of the alarm passed in `<name>`.

This command has the `--output` flag. Use the `--output` flag to specify the response format. Supported values are `table` (default) and `json`.

This command accepts only the default flag `--help`.

[[runtime-mgr-cloudhub-application-list]]
== runtime-mgr:cloudhub-application:list

----
> runtime-mgr:cloudhub-application:list [flags]
----

This command lists all applications available in your Anypoint Platform CLI. It returns your application name, its status, the number of vCores assigned and the last time it was updated.

This command has the `--output` flag. Use the `--output` flag to specify the response format. Supported values are `table` (default) and `json`.

This command also accepts the default flag `--help`.

[[runtime-mgr-cloudhub-application-describe]]
== runtime-mgr:cloudhub-application:describe

----
> runtime-mgr:cloudhub-application:describe [flags] <name>
----

This command displays information on the application you pass in `<name>`. +
Use the flag `-o json` to get the raw JSON response of the application you specify in `<name>`. +
The command returns data such as the application's domain, its status, the last time it was updated, the Mule version, the ZIP file name, the region, monitoring, and workers; as well as `TRUE` or `FALSE` information for persistent queues and static IPs enablement.

This command has the `--output` flag. Use the `--output` flag to specify the response format. Supported values are `table` (default) and `json`.

This command also accepts the default flag `--help`.

// == runtime-mgr:cloudhub-application:describe-json

// ----
// > runtime-mgr:cloudhub-application:describe-json  [options] <name>
// ----

// This command returns the raw JSON response of the application you specify in `<name>`.

// You can start typing your application's name and press `tab` for Anypoint Platform CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass.

// This command accepts only the default options: `--help` and `-o`/`--output`

[[runtime-mgr-cloudhub-application-stop]]
== runtime-mgr:cloudhub-application:stop

----
> runtime-mgr:cloudhub-application:stop  [flags] <name>
----

This command stops the running application you specify in `<name>`.
This command accepts only the default flag `--help`.

[[runtime-mgr-cloudhub-application-start]]
== runtime-mgr:cloudhub-application:start

----
> runtime-mgr:cloudhub-application:start [flags] <name>
----

This command starts the running application you specify in `<name>`.
This command accepts only the default flag `--help`.

[[runtime-mgr-cloudhub-application-restart]]
== runtime-mgr:cloudhub-application:restart

----
> runtime-mgr:cloudhub-application:restart  [flags] <name>
----

This command restarts the running application you specify in `<name>`.

This command accepts only the default flag `--help`.

[[runtime-mgr-cloudhub-application-delete]]
== runtime-mgr:cloudhub-application:delete

----
> runtime-mgr:cloudhub-application:delete [flags] <name>
----

This command deletes the running application you specify in `<name>`.

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

This command accepts only the default flag `--help`.

[[deploy-to-cloudhub]]
== runtime-mgr:cloudhub-application:deploy

----
> runtime-mgr:cloudhub-application:deploy  <name> <zipfile> [flags]
----

This command deploys the Mule deployable archive ZIP file that you specify in `<zipfile>` using the name you set in `<name>`.
You will have to provide the absolute or relative path to the deployable ZIP file in your local hard drive and the name you give to your application has to be unique.

[NOTE]
If successful, this command's output includes the deployment status of `UNDEPLOYED`,
which indicates that CloudHub uploaded the application successfully.

The flags this command can take are:
[%header,cols="30a,70a"]
|===
|Flag |Description
|--runtime                                   | Name and version of the runtime environment. +
Use this flag to specify the name and version of the runtime you want to deploy. +
Some examples of this value are `2.1.1-API-Gateway`, `3.9.1-visualizer` or   `4.1.1`. +
(This value is the latest CloudHub Runtime version by default.)
|--workers                                      | Number of workers. (This value is '1' by default)
|--workerSize                               | Size of the workers in vCores. (This value is '1' by default)
|--region                                        | Name of the region to deploy to. +
For a list of all supported regions, use the xref:anypoint-cli::cloudhub-dlb.adoc#cloudhub-region-list[cloudhub:region:list] command.
|--property                                    | Set a property (`name:value`). +
The property to be set must be passed enclosed in quotes and characters `:` and `=` must be escaped. +
(e.g. `--property "salesforce.password:qa\=34534"`).

Character `:` is not supported for the property's name.
|--propertiesFile                        | Overwrite all properties with values from this file. The file format is 1 or more lines in `name:value` format. Set the absolute path of the properties file in your local hard drive.
|--[no-]persistentQueues                   | Enable or disable persistent queues (This value is `disabled` by default)
|--[no-]persistentQueuesEncrypted  | Enable or disable persistent queue encryption (This value is `disabled` by default)
|--[no-]staticIPsEnabled                                      | Enable or disable static IPs. This value is `disabled` by default.
|--[no-]objectStoreV1                   | Enable or disable Object Store V1. +
`objectStoreV2` cannot also be provided when using `objectStoreV1` flag.
|--[no-]objectStoreV2                   | Enable or disable Object Store V2. +
`objectStoreV1` cannot also be provided when using `objectStoreV2` flag.
|--[no-]autoRestart                            | Automatically restart app when not responding. This value is `enabled` by default.|
--output | Specify the response format. Supported values are `table` (default) and `json`

|--help                                                  |
Output usage information
|--timeout | Set the timeout value in miliseconds. Can take values between `60000` and `300000`.

|===
Note that from Anypoint Platform CLI you won't be able to allocate static IPs. You can simply enable and disable them.


[IMPORTANT]
====
If you deploy without using any flags, your application deploys using all your default values.
====

[NOTE]
====
include::anypoint-cli::partial$mule-4.5-release-channels.adoc[]
====

NOTE: This command has multi-option flags. When using multi-option flags in a command, either put the parameter before the flags or use a `-- ` (two dashes followed by a space) before the parameter.

[[runtime-mgr-cloudhub-application-modify]]
== runtime-mgr:cloudhub-application:modify

----
> runtime-mgr:cloudhub-application:modify  <name> [zipfile] [flags]
----
This command updates the settings of an existing application. Optionally, you can update it by uploading a new ZIP file.
This command can take all the same flags as the `deploy` command.

[NOTE]
This command's output includes `Status`, which is the application's previous deployment status state.

NOTE: This command has multi-option flags. When using multi-option flags in a command, either put the parameter before the flags or use a `-- ` (two dashes followed by a space) before the parameter.



//TODO Check revert-runtime deprecation
// == runtime-mgr application revert-runtime
//
// [source,Example]
// ----
// > runtime-mgr application revert-runtime [options] <name>
// ----
// This command reverts the application defined in `<name>` to its previous runtime environment. +
// You can start typing your application's name and press `tab` for Anypoint Platform CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass.

// CLI DEFAULTS
// include::partial$cli-default-options.adoc[tag=CLIdefaultOptions]

[[runtime-mgr-cloudhub-application-download-logs]]
== runtime-mgr:cloudhub-application:download-logs

----
> runtime-mgr:cloudhub-application:download-logs [flags] <name> <directory>
----
This command downloads logs the for application specified in `<name>` to the specified directory.

Keep in mind that contrarily to what you see in the UI, the logs you download from the CLI won't separate system logs from worker logs.

[[runtime-mgr-cloudhub-application-tail-logs]]
== runtime-mgr:cloudhub-application:tail-logs

----
> runtime-mgr:cloudhub-application:tail-logs [flags] <name>
----

This command tails application logs.

This command accepts only the default flag `--help`.

// == runtime-mgr cloudhub-application upgrade-runtime
//
// [source,Example]
// ----
// > runtime-mgr cloudhub-application upgrade-runtime [options] <name>
// ----
//
// This command upgrades the runtime version of the application passed in `name` to the latest patch version. If the `-v`/`--version` option is used to specify a specific runtime version, this command updates the application's runtime to that version. +
// Besides the `--version` option, this command also has the default `--help`, `-f`/`--fields` and `-o`/`--output` options.
//
// == runtime-mgr cloudhub-application downgrade-runtime
//
// [source,Example]
// ----
// > runtime-mgr cloudhub-application downgrade-runtime [options] <name>
// ----
// This command downgrades the runtime version of the application passed in `name` to the previous runtime version. If the `-v`/`--version` option is used to specify a specific runtime version, this command updates the application's runtime to that version. +
// Besides the `--version` option, this command also has the default `--help`, `-f`/`--fields` and `-o`/`--output` options.

[[runtime-mgr-cloudhub-application-copy]]
== runtime-mgr:cloudhub-application:copy

----
> runtime-mgr:cloudhub-application:copy <source> <target> [flags]
----

This command copies the CloudHub application passed in `source` to the target passed in `target`.

Arguments `source` and `target` should be formatted as follows: `([group_id]/)<asset_id>/<version>`.

If `group_id` is not specified, it defaults to the currently selected Organization ID.

For example:

----
> runtime-mgr:cloudhub-application:copy Services:QA/application-1 Development:QA/application-2
----
Copies the application named `application-1` from the QA environment of the Services organization to the QA environment of the Development organization. +
If the Anypoint Platform CLI is using the QA environment in the Services organization, the command can simply take the application name as a `source`:

----
> runtime-mgr:cloudhub-application:copy application-1 Development/QA/application-2
----

[NOTE]
Running this command requires your user to have read/write access to the `/tmp` directory of the OS where CLI is installed.

In addition to the default `--help`, and `-f`/`--fields`  flags, this command also accepts:

[%header,cols="30a,70a"]
|===
|Flag |Description
|--property  | Set a property (`name:value`).

Enclose the property in quotes and escape the `:` and `=` characters,
for example:

`--property "salesforce.password:qa\=34534"`
|===

NOTE: This command has multi-option flags. When using multi-option flags in a command, either put the parameter before the flags or use a `-- ` (two dashes followed by a space) before the parameter.


[NOTE]
When copying an application containing safely hidden application properties, pass the properties in the `copy` command using the `--property` flag.
For information about safely hidden application properties, see xref:runtime-manager::secure-application-properties.adoc[Safely Hide Application Properties].


[[cloudhub-region-list]]
== cloudhub:region:list

----
> cloudhub:region:list [flags]
----
This command lists all supported regions.

This command has the `--output` flag. Use the `--output` flag to specify the response format. Supported values are `table` (default) and `json`.

This command also accepts the default flag `--help`.

[[cloudhub-runtime-list]]
== cloudhub:runtime:list

----
> cloudhub:runtime:list [flags]
----
This command lists all supported runtimes.

This command accepts only the default flag `--help`.

// end::commands[]
