= CLI for DataGraph API Source Management

// tag::summary[]

[%header,cols="35a,65a"]
|===
|Command |Description
| <<datagraph sources add>> | Adds an API source 
| <<datagraph sources promote>> | Promotes an API source
| <<datagraph sources update>> | Updates an API source
| <<datagraph scale>> | Scales API calls made to the unified schema
| <<datagraph schema-download>> | Downloads the unified schema
| <<datagraph sources delete>> | Deletes an API source
| <<datagraph sources get>> | Gets an API source
| <<datagraph sources list>> | Lists all API sources
| <<datagraph describe>> | Returns information about DataGraph
|===

// end::summary[]

// tag::commands[]

== datagraph sources add

----
> datagraph sources add <gav>
----

This command adds an API source, specified by `<gav>`—the group, asset, and version of the API source. 
 
In addition to the default `--help`, `-f/--fields`, and `-o/--output` options, this command accepts the following default options:

[%header,cols="35a,65a"]
|===
| Options | Description
|`--auth-none` | Use if your API is public.
|`--auth-basic` a|Use if you authenticate to your API using the basic authentication header, or a username and password.
 
Additional required options:

* `--basic-credentials <username>:<password>`

|`--auth-oauth` a| Use if you authenticate to your API by passing OAuth 2.0 `client_id`, `client_secret`, and authorization server values. 

Additional required options:

* `--client-credentials <client_id>:<client_secret>`
* `--<authorization server URL>` 
* `--<scope>`

|`--auth-pass-through` a| Use if you authenticate to your API by passing authorization headers.

Additional required options:

*  `--mapping: <comma-separated list of key:value pairs>`

|`--auth-custom` a|Use if you authenticate to your API using custom header parameters and values, such as query params or headers.

Additional required options for query params:

* `--query-params: <comma-separated list of key:value pairs>`
* `--query-params-file: <location of the file containing query param key:value pairs, one pair per line>`

Additional required options for headers: 

* `--headers: c<omma-separated list of key:value pairs>`
* `--headers-file: <location of the file containing header key:value pairs, one per line>`

|`--url` | Configures the URL for the backend API.
|`--discover-url` | Automatically discovers the URL of the backend API based on the instances running in the current environment. If more than one APIs is running, DataGraph uses the first URL.
|`--ca` | Specify a list of certificate authority (CA) files to add to the API's truststore.
|`--cert` | Specify the client certificate to use for mTLS.
|`--key` | Specify the private key to use for mTLS.
|`--key-password` | Specify the password to decrypt an encrypted private key.
|===

[NOTE]
All headers and query params defined in the command line and the headers and query params files are appended. If there are repeated keys, the values provided in the command line takes precedence.

== datagraph sources promote

----
> datagraph sources promote <sourceId> <targetEnv>
----

This command promotes an API source, specified by its `<sourceId>`, to the target environment, specified by `<targetEnv>`.

In addition to the default `--help`, `-f/--fields`, and `-o/--output` options, this command accepts the following default options:

[%header,cols="30a,40a,30a"]
|===
| Options | Description 
|`--auth-none` | Use if your API is public.
|`--auth-basic` a|Use if you authenticate to your API using the basic authentication header, or a username and password.
 
Additional required options:

* `--basic-credentials <username>:<password>`

|`--auth-oauth` a| Use if you authenticate to your API by passing OAuth 2.0 `client_id`, `client_secret`, and authorization server values. 

Additional required options:

* `--client-credentials <client_id>:<client_secret>`
* `--<authorization server URL>` 
* `--<scope>`

|`--auth-pass-through` a| Use if you authenticate to your API by passing authorization headers.

Additional required options:

*  `--mapping: <comma-separated list of key:value pairs>`

|`--auth-custom` a|Use if you authenticate to your API using custom header parameters and values, such as query params or headers.

Additional required options for query params:

* `--query-params: <comma-separated list of key:value pairs>`
* `--query-params-file: <location of the file containing query param key:value pairs, one pair per line>`

Additional required options for headers: 

* `--headers: c<omma-separated list of key:value pairs>`
* `--headers-file: <location of the file containing header key:value pairs, one per line>`

|`--url` | Configures the URL for the backend API.
|`--discover-url` | Automatically discovers the URL of the backend API based on the instances running in the current environment. If more than one APIs is running, DataGraph uses the first URL.
|`--ca` | Specify a list of certificate authority (CA) files to add to the API's truststore.
|`--cert` | Specify the client certificate to use for mTLS.
|`--key` | Specify the private key to use for mTLS.
|`--key-password` | Specifies the password to decrypt an encrypted private key.
|`--delete-ca` | Deletes all CA certificates.
|`--no-mtls` | Deletes the client certificate, private key, and private key password information.
|===

[NOTE]
All headers and query params defined in the command line and the headers and query params files are appended. If there are repeated keys, the values provided in the command line takes precedence.

== datagraph sources update 

----
> datagraph sources update <sourceId>
----

This command updates the version of an API source, specified by its `<sourceId>`.

In addition to the default `--help`, `-f/--fields`, and `-o/--output` options, this command accepts the following default options:

[%header,cols="30a,40a,30a"]
|===
| Options | Description 
|`--auth-none` | Use if your API is public.
|`--auth-basic` a|Use if you authenticate to your API using the basic authentication header, or a username and password.
 
Additional required options:

* `--basic-credentials <username>:<password>`

|`--auth-oauth` a| Use if you authenticate to your API by passing OAuth 2.0 `client_id`, `client_secret`, and authorization server values. 

Additional required options:

* `--client-credentials <client_id>:<client_secret>`
* `--<authorization server URL>` 
* `--<scope>`

|`--auth-pass-through` a| Use if you authenticate to your API by passing authorization headers.

Additional required options:

*  `--mapping: <comma-separated list of key:value pairs>`

|`--auth-custom` a|Use if you authenticate to your API using custom header parameters and values, such as query params or headers.

Additional required options for query params:

* `--query-params: <comma-separated list of key:value pairs>`
* `--query-params-file: <location of the file containing query param key:value pairs, one pair per line>`

Additional required options for headers: 

* `--headers: c<omma-separated list of key:value pairs>`
* `--headers-file: <location of the file containing header key:value pairs, one per line>`

|`--url` | Configures the URL for the backend API.
|`--discover-url` | Automatically discovers the URL of the backend API based on the instances running in the current environment. If more than one APIs is running, DataGraph uses the first URL.
|`--ca` | Specify a list of certificate authority (CA) files to add to the API's truststore.
|`--cert` | Specify the client certificate to use for mTLS.
|`--key` | Specify the private key to use for mTLS.
|`--key-password` | Specifies the password to decrypt an encrypted private key.
|`--delete-ca` | Deletes all CA certificates.
|`--no-mtls` | Deletes the client certificate, private key, and private key password information.
|===

[NOTE]
All headers and query params defined in the command line and the headers and query params files are appended. If there are repeated keys, the values provided in the command line takes precedence.

== datagraph scale 

----
> datagraph scale <api-calls>
----

This command allows you to configure the number of concurrent API calls, specified by `<api-calls>`, permitted for a unified schema. Increasing or decreasing API calls enables you to process higher workloads and optimize your consumption when needed.

This command takes the default `--help`, `-f/--fields`, and `-o/--output` options.

== datagraph schema-download

----
> datagraph schema-download
----

This command downloads the unified schema for the current environment. 

This command takes the default `--help`, `-f/--fields`, and `-o/--output` options.

== datagraph sources delete

----
> datagraph sources delete <sourceId>
----

This command deletes an API source, specified by `<sourceId>`.

This command takes the default `--help`, `-f/--fields`, and `-o/--output` options.

== datagraph sources get 

----
> datagraph sources get <sourceId>
----

This command get an API source, specified by `<sourceId>`.

This command takes the default `--help`, `-f/--fields`, and `-o/--output` options.

== datagraph sources list

----
> datagraph sources list
----

This command list all API sources for the current environment. 

This command takes the default `--help`, `-f/--fields`, and `-o/--output` options.

== datagraph describe 

----
> datagraph describe
----

This command returns the following information about DataGraph:

* `endpoint`: Displays the GraphQL endpoint that accepts requests.
* `deploymentError`: If a DataGraph deployment fails, this field describes the error; otherwise, it's empty.
* `deploymentStatus`: Shows whether DataGraph is deploying, running, or has errors.
* `logLevels`: Displays a list of the configured log levels.

This command takes the default `--help`, `-f/--fields`, and `-o/--output` options.

