= DataGraph Load Balancers


// tag::summary[]

[%header,cols="35a,65a"]
|===
|Command |Description
| xref:datagraph.adoc#datagraph-load-balancer-config-add[datagraph:load-balancer-config:add] | Adds a dedicated load balancer configuration to Anypoint DataGraph
| xref:datagraph.adoc#datagraph-load-balancer-config-describe[datagraph:load-balancer-config:describe] | Displays a dedicated load balancer configuration for Anypoint DataGraph
| xref:datagraph.adoc#datagraph-load-balancer-config-remove[datagraph:load-balancer-config:remove]| Removes a dedicated load balancer configuration from Anypoint DataGraph
|===


// end::summary[]


// tag::commands[]

[[datagraph-load-balancer-config-add]]
== datagraph:load-balancer-config:add

----
> datagraph:load-balancer-config:add <dlbUrl>
----
This command adds a dedicated load balancer configuration specified by `<dlbUrl>` to Anypoint DataGraph.
The `dlbUrl` is a valid URL that includes the DLB domain and the mapping rule `inputUri`.


This command accepts only the default option `--help`.

[[datagraph-load-balancer-config-describe]]
== datagraph:load-balancer-config:describe

----
> datagraph:load-balancer-config:describe [options]
----

This command displays a dedicated load balancer URL for Anypoint DataGraph.

This command has the `--output` option. Use the `--output` option to specify the response format. Supported values are `table` (default) and `json`

This command also accepts the default option `--help`.

[[datagraph-load-balancer-config-remove]]
== datagraph:load-balancer-config:remove

----
> datagraph:load-balancer-config:remove [options]
----

This command removes a dedicated load balancer configuration from Anypoint DataGraph.

This command accepts only the default option `--help`.

// end::commands[]
