= Design Center Projects


// tag::summary[]

[%header,cols="35a,65a"]
|===
|Command |Description
| xref:anypoint-cli::design-center.adoc#designcenter-project-create[designcenter:project:create] | Creates a new Design Center project
| xref:anypoint-cli::design-center.adoc#designcenter-project-delete[designcenter:project:delete] | Deletes a Design Center project
| xref:anypoint-cli::design-center.adoc#designcenter-project-download[designcenter:project:download] | Downloads the content of a Design Center project
| xref:anypoint-cli::design-center.adoc#designcenter-project-publish[designcenter:project:publish] | Publishes a Design Center project to Exchange
| xref:anypoint-cli::design-center.adoc#designcenter-project-upload[designcenter:project:upload] | Uploads the content of a project to Design Center
| xref:anypoint-cli::design-center.adoc#designcenter-project-list[designcenter:project:list] | Lists all Design Center projects
|===

// end::summary[]

// tag::commands[]

[[designcenter-project-create]]
== designcenter:project:create

----
> designcenter:project:create [flags] <name>
----

This Command creates a new Design Center project with the name specified in `<name>`.

[IMPORTANT]
This command does not support Mule application types.


Besides the default `--help` flag, this command also accepts:

[%header,cols="30a,40a,30a"]
|===
|Flag | Description |  Example
| `--type (required)` | The project type. +
This field is required.

Supported values are:

* `raml`
* `raml-fragment` | `--type raml`
| `--fragmentType` | The fragment type. Always use with `--type raml-fragment`, even for OAS 3.0 and JSON schema fragments.

This field is required if the type flag was set as `raml-fragment`

Supported fragments type are:

* `trait`
* `resource-type`
* `library`
* `type`
* `user-documentation` 
* `oas-components`
* `json-schema`| `--type raml-fragment --fragmentType user-documentation`
|`--output` | Specify the response format. |`--output json`

|===

[[designcenter-project-delete]]
== designcenter:project:delete

----
> designcenter:project:delete [flags] <name>
----

This Command deletes the Design Center project specified in `name`.

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

This command accepts only the default flag `--help`.

[[designcenter-project-download]]
== designcenter:project:download

----
> designcenter:project:download [flags] <name> <targetDir>
----

This command downloads the Design Center project passed in `name` to your local directory specified in `targetDir`.

Use the `--resolveDependenciesTimeout=X` flag to specify the duration, in minutes, for which the system should await the resolution of dependencies before downloading a project.

This command also accepts the default flag `--help`.


[[designcenter-project-publish]]
== designcenter:project:publish

----
> designcenter:project:publish [flags] <projectName>
----

This Command publishes the Design Center project passed in `projectName` to Exchange. +
Besides the default `--help` flag, this command also accepts:

[TIP]
Flags that are not specified are extracted from exchange.json

[%header,cols="30a,40a,30a"]
|===
|Flag | Description |  Example
| `--name` | The name for the asset | `--name sampleProject`
| `--main` | The name of the main file name. | `--main sample.xml`
| `--apiVersion` | The API version if your project is an API specification project. | `--main sample.raml --apiVersion 1.0`
| `--tags` | Comma separated list of tags. | `--tags test,sample,integration`
| `--groupId` | The asset's groupId. | `designcenter:project:publish --groupId com.mulesoft.com`
| `--assetId`  | The asset's assetId. | `designcenter:project:publish --assetId project`
| `--version` | The asset's version. | `designcenter:project:publish --version 1.0`
|===

[[designcenter-project-upload]]
== designcenter:project:upload

----
> designcenter:project:upload [flags] <name> <projDir>
----

This Command uploads content from a Design Center project from your local directory passed in `projDir` into an already existing Design Center project identified with `name`.

By default, this command ignores all hidden files and directories. To include hidden files and directories, use the `--include-dot-files` flag. 
When the `--include-dot-files` flag is used, the command uploads hidden files and folders from your specified directory.

Besides the `--include-dot-files`, this command has the default `--help` flag.

[[designcenter-project-list]]
== designcenter:project:list

----
> designcenter:project:list [flags] [searchText]
----

This Command lists all your Design Center projects. +

Besides the default `--help` flag, this command also accepts:

[%header,cols="30a,40a,30a"]
|===
|Flag | Description |  Example
|`--pageIndex` | Number of page to retrieve | `--pageIndex 3`
|`--pageSize` | Number of results to retrieve per page | `--pageSize 5`
|`--output` | Specify the response format. | `--output json`

|===

// end::commands[]