= Design Center Projects


// tag::summary[]

[%header,cols="35a,65a"]
|===
|Command |Description
| <<designcenter project create>> | Creates a new Design Center project
| <<designcenter project delete>> | Deletes a Design Center project
| <<designcenter project download>> | Downloads the content of a Design Center project
| <<designcenter project publish>> | Publishes a Design Center project to Exchange
| <<designcenter project upload>> | Uploads the content of a project to Design Center
| <<designcenter project list>> | List all Design Center projects
|===

// end::summary[]

// tag::commands[]
== designcenter project create

----
> designcenter project create [options] <name>
----

This Command creates a new Design Center project with the name specified in `<name>`.

[IMPORTANT]
This command does not support Mule application types.

Besides the default `--help`, `-f`/`--fields` and `-o`/`--output` options, this command also takes:

[%header,cols="30a,40a,30a"]
|===
|Option | Description |  Example
| `--type (required)` | The project type. +
This field is required.

Supported values are:

* `raml`
* `raml-fragment` | `designcenter project create --type raml`
| `--fragment-type` | The fragment type. Always use with `--type raml-fragment`, even for OAS 3.0 and JSON schema fragments.

This field is required if the type option was set as `raml-fragment`

Supported fragments type are:

* `trait`
* `resource-type`
* `library`
* `type`
* `user-documentation` 
* `oas-components`
* `json-schema` | `designcenter project create --type raml-fragment --fragment-type user-documentation`
|===

== designcenter project delete

----
> designcenter project delete [options] <name>
----

This Command deletes the Design Center project specified in `name`.

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

This command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.

== designcenter project download

----
> designcenter project download [options] <name> <targetDir>
----

This command downloads the Design Center project passed in `name` to your local directory specified in `targetDir`.

Use the `--branch` option to select the branch you want to download content from.
Use the `--resolveDependenciesTimeout=X` flag to specify the duration, in minutes, for the commands to wait for the resolution of dependencies before downloading a project. If the specified time passes, your project downloads without the missing dependencies.


This command also accepts the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.


== designcenter project publish

----
> designcenter project publish [options] <projectName>
----

This Command publishes the Design Center project passed in `projectName` to Exchange. +
Besides the default `--help`, `-f`/`--fields` and `-o`/`--output` options, this command also takes:

[TIP]
Options that are not specified are extracted from exchange.json

[%header,cols="30a,40a,30a"]
|===
|Option | Description |  Example
| `--name` | The name for the asset | `designcenter project publish --name sampleProject`
| `--main` | The name of the main file name. | `designcenter project publish --main sample.xml`
| `--apiVersion` | The API version if your project is an API specification project. | `designcenter project publish --main sample.raml --apiVersion 1.0`
| `--tags` | Comma separated list of tags. | `designcenter project publish --tags test,sample,integration`
| `--groupId` | The asset's groupId. | `designcenter project publish --groupId com.mulesoft.com`
| `--assetId`  | The asset's assetId. | `designcenter project publish --assetId project`
| `--version` | The asset's version. | `designcenter project publish --version 1.0`
| `--branch` | The asset's branch. | `designcenter project publish --branch main`
|===

== designcenter project upload

----
> designcenter project upload [options] <name> <projDir>
----

This Command uploads content from a Design Center project from your local directory passed in `projDir` into an already existing Design Center project identified with `name`.

By default, this command ignores all hidden files and directories. To include hidden files and directories, use the `--include-dot-files` option. 
When the `--include-dot-files` option is used, the command uploads hidden files and folders from your specified directory.

Use the `--branch` option to select the branch you want to upload content to.

This command also accepts the default `--help`, `-f`/`--fields` and `-o`/`--output` options.

== designcenter project list

----
> designcenter project list [options] [searchText]
----

This Command lists all your Design Center projects. +
You can start typing your project's name and press `tab` for Anypoint Platform CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass. +

Besides the default `--help`, `-f`/`--fields` and `-o`/`--output` options, this command also takes:

[%header,cols="30a,40a,30a"]
|===
|Option | Description |  Example
|`--pageIndex` | Number of page to retrieve | `designcenter project list --pageIndex 3`
|`--pageSize` | Number of results to retrieve per page | `designcenter project list --pageSize 5`
|===

// end::commands[]
