= Use Anypoint Platform CLI

// tag::usageintro[]

Use Anypoint Platform CLI commands to automate a subset of product actions through scripts. Anypoint Platform CLI 4.0 and later can be run only in batch mode. 

// end::usageintro[]

// tag::syntax[]

== Syntax

The Anypoint Platform CLI command set has the following syntax:

// [source,console]
// I commented out source,console out because the command shows as yellow, which is an accessibility issue when using a white background. We can research a better color scheme for commands if it is necessary.

----
$ anypoint-cli [command] [options]
----

If you pass a command and there is an error, the application exits and returns a description of the issue.

[[default-options]]
== Default Options

Anypoint Platform CLI has the following default options:

* `--help` displays usage information of the command.
* `-f` or `--fields` specifies which fields to output. 
+
You can use the `--fields` option with no fields to get a list of fields to output.
* `-o` or `--output` outputs the results in one of the following formats: +
** `table`
** `text`
** `json`
+
The default is `text`.

// end::syntax[]
