= Use Anypoint Platform CLI

// Check this for 4.x, as I think interactive mode will no longer be supported.  

Use Anypoint Platform CLI commands to automate a subset of product actions through scripts. 

Anypoint Platform CLI can be run in batch or interactive mode. 

// tag::syntax[]

== Syntax

The Anypoint Platform CLI command set has the following syntax:

// [source,console]
// I commented out source,console out because the command shows as yellow, which is an accessibility issue when using a white background. We can research a better color scheme for commands if it is necessary.

----
$ anypoint-cli [params] [command]
----

If you pass a command and there is an error, the application exits and returns a description of the issue.

[[default-options]]
== Default Options

Anypoint Platform CLI has the following default options:

* `--help` displays usage information of the command.
* `-f` or `--fields` specifies which fields to output. 
+
You can use the `--fields` option with no fields to get a list of fields to output.
* `-o` or `--output` outputs the results in one of the following formats: +
** `table`
** `text`
** `json`
+
The default is `text` for non-interactive mode and `table` for interactive mode.

// end::syntax[]


// tag::commands[]

[[interactive-mode]]
== Interactive Mode

If you do not to pass a command, Anypoint Platform CLI runs in interactive mode.


=== exit

----
> exit [options]
----
This command exits Anypoint Platform CLI when it is being run in interactive mode.

The `exit` command accepts only the default options: `--help`, `-f`/`--fields` and `-o`/`--output`.



// end::commands[]
