= Local Server Groups

// tag::summary[]

[%header,cols="35a,65a"]
|===
|Command |Description
|xref:server-groups.adoc#runtime-mgr-servergroup-create[runtime-mgr:serverGroup:create] | Creates server group from servers
|xref:server-groups.adoc#runtime-mgr-servergroup-describe[runtime-mgr:serverGroup:describe] | Describes server group
|xref:server-groups.adoc#runtime-mgr-servergroup-modify[runtime-mgr:serverGroup:modify] | Modifies server group
|xref:server-groups.adoc#runtime-mgr-servergroup-add-server[runtime-mgr:serverGroup:add:server] | Adds server to a server group
|xref:server-groups.adoc#runtime-mgr-servergroup-delete[runtime-mgr:serverGroup:delete] | Deletes server group
|xref:server-groups.adoc#runtime-mgr-servergroup-list[runtime-mgr:serverGroup:list] | Lists all server groups in the environment
|xref:server-groups.adoc#runtime-mgr-servergroup-remove-server[runtime-mgr:serverGroup:remove:server] | Removes server from a server group
|===

// end::summary[]

// tag::commands[]

[[runtime-mgr-servergroup-create]]
== runtime-mgr:serverGroup:create

----
> runtime-mgr:serverGroup:create [options] <name> [serverIds...]
----

This command creates a server group with the name passed in `name` using the server Id(s) passed as argument(s) thereafter.

This command accepts only the default option `--help`.

[[runtime-mgr-servergroup-describe]]
== runtime-mgr:serverGroup:describe

----
> runtime-mgr:serverGroup:describe [options] <serverGroupId>
----

This command describes the server group passed in `serverGroupId`.

This command has the `--output` option. Use the `--output` option to specify the response format. Supported values are `table` (default) and `json`.

This command also accepts the default option `--help`.

[[runtime-mgr-servergroup-modify]]
== runtime-mgr:serverGroup:modify

----
> runtime-mgr:serverGroup:modify [options] <serverGroupId>
----

This command modifies the server group passed in `serverGroupId`.

In order to update the id for the cluster, you need to pass the  `--name` option.

Besides the `--name` option, this command also has the default `--help`, and `-f`/`--fields` options.

[[runtime-mgr-servergroup-add-server]]
== runtime-mgr:serverGroup:add:server

----
> runtime-mgr:serverGroup:add:server [options] <serverGroupId> <serverId>
----

This command adds the server passed in `serverId` to the server group passed in `serverGroupId`.

This command accepts only the default option `--help`.

[[runtime-mgr-servergroup-delete]]
== runtime-mgr:serverGroup:delete

----
> runtime-mgr:serverGroup:delete [options] <serverGroupId>
----

This command deletes the server groups passed in `serverGroupId`.

This command accepts only the default option `--help`.

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

[[runtime-mgr-servergroup-list]]
== runtime-mgr:serverGroup:list

----
> runtime-mgr:serverGroup:list [options]
----

This command lists all server groups in the environment.

This command has the `--output` option. Use the `--output` option to specify the response format. Supported values are `table` (default) and `json`.

This command also accepts the default option `--help`.

[[runtime-mgr-servergroup-remove-server]]
== runtime-mgr:serverGroup:remove:server

----
> runtime-mgr:serverGroup:remove:server [options] <serverGroupId> <serverId>
----

This command removes the server passed in `serverId` from the server group passed in `serverGroupId`.

This command accepts only the default option `--help`.

// end::commands[]
