= Local Server Clusters

// tag::summary[]

[%header,cols="35a,65a"]
|===
|Command |Description
|xref:anypoint-cli::server-clusters.adoc#runtime-mgr-cluster-add-server[runtime-mgr:cluster:add:server] | Adds server to cluster
|xref:anypoint-cli::server-clusters.adoc#runtime-mgr-cluster-create[runtime-mgr:cluster:create] | Creates new cluster
|xref:anypoint-cli::server-clusters.adoc#runtime-mgr-cluster-describe[runtime-mgr:cluster:describe] | Describes server cluster
|xref:anypoint-cli::server-clusters.adoc#runtime-mgr-cluster-delete[runtime-mgr:cluster:delete] | Deletes cluster
|xref:anypoint-cli::server-clusters.adoc#runtime-mgr-cluster-modify[runtime-mgr:cluster:modify] | Modifies cluster
|xref:anypoint-cli::server-clusters.adoc#runtime-mgr-cluster-list[runtime-mgr:cluster:list] | Lists all clusters in the environment
|xref:anypoint-cli::server-clusters.adoc#runtime-mgr-cluster-remove-server[runtime-mgr:cluster:remove:server] | Removes server from a cluster
|===

// end::summary[]


// tag::commands[]

[[runtime-mgr-cluster-add-server]]
== runtime-mgr:cluster:add:server

----
> runtime-mgr:cluster:add:server [flags] <clusterId> <serverId>
----

Adds the cluster in `clusterId` to the server passed in `serverId`.

This command accepts the xref:index.adoc#default-options[default flags].

[[runtime-mgr-cluster-create]]
== runtime-mgr:cluster:create

----
> runtime-mgr:cluster:create <name> [flags]
----

This command creates a cluster using the id passed in `name`.

In addition to the xref:index.adoc#default-options[default flags], this command accepts the following flags:

[%header,cols="30a,40a,30a"]
|===
|Flag | Description| Example
|`--multicast` | Whether cluster should be multicast | `--multicast`
|`--server` | Pair of server ID and IP address +
 IP address is optional for multicast cluster +
  Provide multiple values to add multiple servers
| `--server 903083:192.168.0.1`
|===

NOTE: This command has multi-option flags. When using multi-option flags in a command, either put the parameter before the flags or use a `-- ` (two dashes followed by a space) before the parameter.

[[runtime-mgr-cluster-describe]]
== runtime-mgr:cluster:describe

----
> runtime-mgr:cluster:describe [flags] <clusterId>
----

Describes the cluster passed in `clusterId`.

This command accepts the `--output` flag. Use the `--output` flag to specify the response format. Supported values are `table` (default) and `json`.

This command accepts the xref:index.adoc#default-options[default flags].


[[runtime-mgr-cluster-delete]]
== runtime-mgr:cluster:delete

----
> runtime-mgr:cluster:delete [flags] <clusterId>
----

Deletes the cluster passed in `clusterId`.

This command accepts the xref:index.adoc#default-options[default flags].

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

[[runtime-mgr-cluster-list]]
== runtime-mgr:cluster:list

----
> runtime-mgr:cluster:list [flags]
----

Lists all clusters in the environment.

This command has the `--output` flag. Use the `--output` flag to specify the response format. Supported values are `table` (default) and `json`.

This command accepts the xref:index.adoc#default-options[default flags].

[[runtime-mgr-cluster-modify]]
== runtime-mgr:cluster:modify

----
> runtime-mgr:cluster:modify [flags] <clusterId>
----

Modifies the cluster passed in `clusterId`. +
In order to update the id for the cluster, you need to pass the  `--name` flag.

This command accepts the xref:index.adoc#default-options[default flags].

[[runtime-mgr-cluster-remove-server]]
== runtime-mgr:cluster:remove:server

----
> runtime-mgr:cluster:remove:server [flags] <clusterId> <serverId>
----

Removes the server passed in `serverId` from the cluster passed in `clusterId`.

This command accepts the xref:index.adoc#default-options[default flags].

// end::commands[]
