= Local Cluster Servers

// tag::summary[]

[%header,cols="35a,65a"]
|===
|Command |Description
|<<runtime-mgr-cluster:add-server>> | Adds server to cluster
|<<runtime-mgr-cluster-delete>> | Deletes cluster
|<<runtime-mgr-cluster-list>> | Lists all clusters in the environment
|<<runtime-mgr-cluster:remove-server>> | Removes server from a cluster
|<<runtime-mgr-cluster-create>> | Creates new cluster
|<<runtime-mgr-cluster-describe>> | Describes server cluster
|<<runtime-mgr-cluster-modify>> | Modifies cluster
|===

// end::summary[]


// tag::commands[]

[[runtime-mgr-cluster-add-server]]
== runtime-mgr:cluster:add:server

----
> runtime-mgr:cluster:add:server [options] <clusterId> <serverId>
----

This command adds the cluster in `clusterId` to the server passed in `serverId`.

This command accepts only the default option `--help`.

[[runtime-mgr-cluster-delete]]
== runtime-mgr:cluster:delete

----
> runtime-mgr:cluster:delete [options] <clusterId>
----

This command deletes the cluster passed in `clusterId`.

This command accepts only the default option `--help`.

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

[[runtime-mgr-cluster-list]]
== runtime-mgr:cluster:list

----
> runtime-mgr:cluster:list [options]
----

This command lists all clusters in the environment.

This command has the `--output` option. Use the `--output` option to specify the response format. Supported values are `table` (default) and `json`.

This command also accepts the default option `--help`.

[[runtime-mgr-cluster-remove-server]]
== runtime-mgr:cluster:remove:server

----
> runtime-mgr:cluster:remove:server [options] <clusterId> <serverId>
----

This command removes the server passed in `serverId` from the cluster passed in `clusterId`.

This command accepts only the default option `--help`.

[[runtime-mgr-cluster-create]]
== runtime-mgr:cluster:create

----
> runtime-mgr:cluster:create [options] <name>
----

This command creates a cluster using the id passed in `name`.

Besides the default `--help` option, this command also accepts:
[%header,cols="30,70"]
|===
|Value | Description
|`--multicast` | Whether cluster should be multicast
|`--server <id:ip>` | Pair of server ID and IP address. Latter is optional for multicast cluster. Provide multiple values to add multiple servers
|===

[[runtime-mgr-cluster-describe]]
== runtime-mgr:cluster:describe

----
> runtime-mgr:cluster:describe [options] <clusterId>
----

This command describes the cluster passed in `clusterId`.

This command has the `--output` option. Use the `--output` option to specify the response format. Supported values are `table` (default) and `json`.

This command also accepts the default option `--help`.

[[runtime-mgr-cluster-modify]]
== runtime-mgr:cluster:modify

----
> runtime-mgr:cluster:modify [options] <clusterId>
----

This command modifies the cluster passed in `clusterId`. +
In order to update the id for the cluster, you need to pass the  `--name` option.

Besides the `--name` option, this command also has the default `--help`,and `-f`/`--fields` options.

// end::commands[]
