= Local Servers


// tag::summary[]

[%header,cols="35a,65a"]
|===
|Command |Description
|xref:servers.adoc#runtime-mgr-server-describe[runtime-mgr:server:describe] | Describes server
|xref:servers.adoc#runtime-mgr-server-modify[runtime-mgr:server:modify] | Modifies server
|xref:servers.adoc#runtime-mgr-server-token[runtime-mgr:server:token] | Gets server registration token. This token needs to be used to register a new server
|xref:servers.adoc#runtime-mgr-server-delete[runtime-mgr:server:delete] | Deletes server
|xref:servers.adoc#runtime-mgr-server-list[runtime-mgr:server:list] | Changes an standalone application artifact
// |xref:servers.adoc#runtime-mgr-server-register[runtime-mgr server register] | Registers a new server. Returns a signed certificate which is downloaded to the `directory` path
|===

// end::summary[]

// tag::commands[]

[[runtime-mgr-server-describe]]
== runtime-mgr:server:describe

----
> runtime-mgr:server:describe [options] <serverId>
----

This command describes the server passed in `serverId`.

This command has only the default options: `--help` and `-o`/`--output`

[[runtime-mgr-server-modify]]
== runtime-mgr:server:modify

----
> runtime-mgr:server:modify [options] <serverId>
----

This command modifies the server passed in `serverId`.

In order to update the id for the cluster, you need to pass the  `--name` option.

Besides the `--name` option, this command also has the default `--help`, `-f`/`--fields` and `-o`/`--output` options.

[[runtime-mgr-server-token]]
== runtime-mgr:server:token

----
> runtime-mgr:server:token [options]
----

This command gets server registration token. This token needs to be used to register a new server.

This command has only the default options: `--help` and `-o`/`--output`

[[runtime-mgr-server-delete]]
== runtime-mgr:server:delete

----
> runtime-mgr:server:delete [options] <serverId>
----

This command deletes the server passed in `serverId`.

This command has only the default options: `--help` and `-o`/`--output`

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

[[runtime-mgr-server-list]]
== runtime-mgr:server:list

----
> runtime-mgr:server:list [options]
----

This server lists all servers in your environment.

This command has only the default options: `--help` and `-o`/`--output`

