= Local Cluster Servers

// tag::summary[]

[%header,cols="35a,65a"]
|===
|Command |Description
|xref:server-clusters.adoc#runtime-mgr-cluster-add-server[runtime-mgr:cluster:add:server] | Adds server to cluster
|xref:server-clusters.adoc#runtime-mgr-cluster-delete[runtime-mgr:cluster:delete] | Deletes cluster
|xref:server-clusters.adoc#runtime-mgr-cluster-list[runtime-mgr:cluster:list] | Lists all clusters in the environment
|xref:server-clusters.adoc#runtime-mgr-cluster-remove-server[runtime-mgr:cluster:remove:server] | Removes server from a cluster
|xref:server-clusters.adoc#runtime-mgr-cluster-create[runtime-mgr:cluster:create] | Creates new cluster
|xref:server-clusters.adoc#runtime-mgr-cluster-describe[runtime-mgr:cluster:describe] | Describes server cluster
|xref:server-clusters.adoc#runtime-mgr-cluster-modify[runtime-mgr:cluster:modify] | Modifies cluster
|===

// end::summary[]


// tag::commands[]

[[runtime-mgr-cluster-add-server]]
== runtime-mgr:cluster:add:server

----
> runtime-mgr:cluster:add:server [flags] <clusterId> <serverId>
----

This command adds the cluster in `clusterId` to the server passed in `serverId`.

This command accepts only the default flag `--help`.

[[runtime-mgr-cluster-delete]]
== runtime-mgr:cluster:delete

----
> runtime-mgr:cluster:delete [flags] <clusterId>
----

This command deletes the cluster passed in `clusterId`.

This command accepts only the default flag `--help`.

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

[[runtime-mgr-cluster-list]]
== runtime-mgr:cluster:list

----
> runtime-mgr:cluster:list [flags]
----

This command lists all clusters in the environment.

This command has the `--output` flag. Use the `--output` flag to specify the response format. Supported values are `table` (default) and `json`.

This command also accepts the default flag `--help`.

[[runtime-mgr-cluster-remove-server]]
== runtime-mgr:cluster:remove:server

----
> runtime-mgr:cluster:remove:server [flags] <clusterId> <serverId>
----

This command removes the server passed in `serverId` from the cluster passed in `clusterId`.

This command accepts only the default flag `--help`.

[[runtime-mgr-cluster-create]]
== runtime-mgr:cluster:create

----
> runtime-mgr:cluster:create <name> [flags]
----

This command creates a cluster using the id passed in `name`.

Besides the default `--help` flag, this command also accepts:
[%header,cols="30,70"]
|===
|Flag | Description
|`--multicast` | Whether cluster should be multicast
|`--server <id:ip>` | Pair of server ID and IP address. Latter is optional for multicast cluster. Provide multiple values to add multiple servers
|===

NOTE: This command has multi-option flags. When using multi-option flags in a command, either put the parameter before the flags or use a `-- ` (two dashes followed by a space) before the parameter.


[[runtime-mgr-cluster-describe]]
== runtime-mgr:cluster:describe

----
> runtime-mgr:cluster:describe [flags] <clusterId>
----

This command describes the cluster passed in `clusterId`.

This command has the `--output` flag. Use the `--output` flag to specify the response format. Supported values are `table` (default) and `json`.

This command also accepts the default flag `--help`.

[[runtime-mgr-cluster-modify]]
== runtime-mgr:cluster:modify

----
> runtime-mgr:cluster:modify [flags] <clusterId>
----

This command modifies the cluster passed in `clusterId`. +
In order to update the id for the cluster, you need to pass the  `--name` flag.

Besides the `--name` flag, this command also has the default `--help` flag.

// end::commands[]
