= Locally Deployed Applications Managed by Runtime Manager

// tag::summary[]

For the Anypoint Platform CLI to recognize your target servers, each server must be manually registered with the platform.

[%header,cols="35a,65a"]
|===
|Command |Description
|xref:standalone-apps.adoc#runtime-mgr-standalone-application-artifact[runtime-mgr:standalone-application:artifact] | Downloads a standalone application artifact binary
|xref:standalone-apps.adoc#runtime-mgr-standalone-application-deploy[runtime-mgr:standalone-application:deploy] | Deploys or redeploys an application to an on-premises server, server group, or cluster
// |xref:standalone-apps.adoc#runtime-mgr-standalone-application-describe-json[runtime-mgr:standalone-application:describe-json] | Shows a raw standalone application JSON response
|xref:standalone-apps.adoc#runtime-mgr-standalone-application-modify[runtime-mgr:standalone-application:modify] | Changes a standalone application artifact
|xref:standalone-apps.adoc#runtime-mgr-standalone-application-start[runtime-mgr:standalone-application:start] | Starts a standalone application
|xref:standalone-apps.adoc#runtime-mgr-standalone-application-delete[runtime-mgr:standalone-application:delete] | Deletes a standalone application
|xref:standalone-apps.adoc#runtime-mgr-standalone-application-describe[runtime-mgr:standalone-application:describe] | Shows detailed information for a standalone application
|xref:standalone-apps.adoc#runtime-mgr-standalone-application-list[runtime-mgr:standalone-application:list] | Lists all standalone applications in the environment
|xref:standalone-apps.adoc#runtime-mgr-standalone-application-restart[runtime-mgr:standalone-application:restart] | Restarts a standalone application
|xref:standalone-apps.adoc#runtime-mgr-standalone-application-stop[runtime-mgr:standalone-application:stop] | Stops a standalone application
|xref:standalone-apps.adoc#runtime-mgr-standalone-application-copy[runtime-mgr:standalone-application:copy] | Copies a standalone application
|===

// end::summary[]


// tag::commands[]

[[runtime-mgr-standalone-application-artifact]]
== runtime-mgr:standalone-application:artifact

----
> runtime-mgr:standalone-application:artifact [options] <identifier> <directory>
----

This command downloads the application artifact of the `identifier` application, to the directory passed in `directory`.
The `identifier` option can be either an application ID or name.

This command has only the default options: `--help` and `-o`/`--output`

[[runtime-mgr-standalone-application-deploy]]
== runtime-mgr:standalone-application:deploy

----
> runtime-mgr:standalone-application:deploy [options] <targetIdentifier> <name> <zipfile>
----

This command deploys or redeploys the application passed as a ZIP file in the path `zipfile` to the on-premises target passed in `targetIdentifier`.

The `targetIdentifier` option can be either a target ID or name.

A target can be either a server, server group, or cluster.

This command has only the default options: `--help` and `-o`/`--output`

To redeploy an app and set a logging level or turn on Insight event tracking, see <<runtime-mgr:standalone-application:modify>>.

// == runtime-mgr:standalone-application:describe-json

//----
//> runtime-mgr:standalone-application:describe-json [options] <identifier>
//----

//This command describes the standalone (on-premises) application passed in `identifier` as a raw JSON response.

//This command has only the default options: `--help` and `-o`/`--output`

[[runtime-mgr-standalone-application-modify]]
== runtime-mgr:standalone-application:modify

----
> runtime-mgr:standalone-application:modify [options] <identifier> <zipfile>
----

This command modifies the standalone (on-premises) application passed in `identifier` with the ZIP file application passed in `zipfile` as a path.

The `identifier` option specifies the application identifier.
To retrieve the identifier, see
xref:anypoint-cli::standalone-apps.adoc#runtime-mgr-standalone-application-list[runtime-mgr:standalone-application:list].

In addition to the default `--help`, `-f`/`--fields` and `-o`/`--output` options, this command also has:

[%header,cols="30,50a"]
|===
|Value |Description
| `--insight` | Stores message metadata of every Mule transaction.
| `--log [level:scope]` | Sets the logging level and scope pair:

* `level`: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, or OFF
* `scope`: package name of the class, connector, or module to log, such as `org.mule.extension.ftp` for Anypoint Connector for FTP

To set multiple logging levels, provide multiple `--log` options, for example, `--log INFO:org.apache --log WARN:org.mule`.
|===

[[runtime-mgr-standalone-application-start]]
== runtime-mgr:standalone-application:start

----
> runtime-mgr:standalone-application:start [options] <identifier>
----

This command starts the standalone (on-premises) application passed in `identifier`.

This command has only the default options: `--help` and `-o`/`--output`

[[runtime-mgr-standalone-application-delete]]
== runtime-mgr:standalone-application:delete

----
> runtime-mgr:standalone-application:delete [options] <identifier>
----

This command deletes the standalone (on-premises) application passed in `identifier`.

This command has only the default options: `--help` and `-o`/`--output`

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

[[runtime-mgr-standalone-application-describe]]
== runtime-mgr:standalone-application:describe

----
> runtime-mgr:standalone-application:describe [options] <identifier>
----

This command shows detailed information, such as status, creation date, and last update, for the standalone (on-premises) application passed in `identifier`.

Use the option `-o json` to get the raw JSON response of the application you specify in `<name>`. 

This command has only the default options: `--help` and `-o`/`--output`

[[runtime-mgr-standalone-application-list]]
== runtime-mgr:standalone-application:list

----
> runtime-mgr:standalone-application:list [options]
----

This command lists all standalone (on-premises) applications.

Besides the default `--help` and `-o`/`--output` options, this command also has:

[%header%autowidth.spread,cols="a,a"]
|===
|Value |Description
| `--limit <num>` | Specifies the number of results to retrieve
| `--offset <num>`      | Offsets the number of applications passed
|===

[[runtime-mgr-standalone-application-restart]]
== runtime-mgr:standalone-application:restart

----
> runtime-mgr:standalone-application:restart [options] <identifier>
----

This command restarts the standalone (on-premises) application passed in `identifier`.

This command has only the default options: `--help` and `-o`/`--output`

[[runtime-mgr-standalone-application-stop]]
== runtime-mgr:standalone-application:stop

----
> runtime-mgr:standalone-application:stop [options] <identifier>
----

This command stops the standalone (on-premises) application passed in `identifier`.

This command has only the default options: `--help` and `-o`/`--output`

[[runtime-mgr-standalone-application-copy]]
== runtime-mgr:standalone-application:copy

----
> runtime-mgr:standalone-application:copy [options] <source> <target> <targetIdentifier>
----

This command copies the standalone (on-premises) application passed in `source` to the target passed in `target` and the server, server group or cluster ID or Name passed in `targetIdentifier`.

Both arguments `source` and `destination` are represented using the format: `<organizationName>:<environmentName>/<appName>`, for example:

----
> runtime-mgr:standalone-application:copy Services:QA/application-1 Development:QA/application-2 123456
----
Copies the application named `application-1` from the QA environment of the _Services_ organization to the QA environment of the `_Development_` organization in the server ID 123456.

If the Anypoint Platform CLI is using the QA environment in the Services organization, the command can simply take the application name as a `source`:

----
> runtime-mgr:standalone-application:copy application-1 Development/QA/application-2 123456
----

[NOTE]
Running this command requires for your user to have read/write access to the `/tmp` directory of the OS where the CLI is installed.

This command has only the default options: `--help` and `-o`/`--output`

// end::commands[]
